const url = window.location.pathname;
const filename = url.substring(url.lastIndexOf('/')+1);
const optVal = (filename === "index2.html") ? "S" : "";
strHTML = '<option value="">--Select Location--</option>';
strHTML += '<optgroup label="Center">';
strHTML += '<option value="Bryant ALC">Bryant ALC</option>';
strHTML += '<option value="Burke School">Burke School</option>';
strHTML += '<option value="Cedar Lane Center">Cedar Lane Center</option>';
strHTML += '<option value="Davis Vocational Center">Davis Vocational Center</option>';
strHTML += '<option value="Lorton Center">Lorton Center</option>';
strHTML += '<option value="Montrose ALC">Montrose ALC</option>';
strHTML += '<option value="Pimmit Hills Center">Pimmit Hills Center</option>';
strHTML += '<option value="Plum Center">Plum Center</option>';
strHTML += '<option value="Pulley Center">Pulley Center</option>';
strHTML += '<option value="Quander Road Center">Quander Road Center</option>';
strHTML += '</optgroup><optgroup label="Community">';
strHTML += '<option value="Baileys Community Center">Baileys Community Center</option>';
strHTML += '<option value="Falls Church Community Center">Falls Church Community Center</option>';
strHTML += '<option value="Graham Road Community Center">Graham Road Community Center</option>';
strHTML += '<option value="Gum Springs Community Ctr">Gum Springs Community Ctr</option>';
strHTML += '<option value="Herndon Community Center">Herndon Community Center</option>';
strHTML += '<option value="Huntington Community Center">Huntington Community Center</option>';
strHTML += '<option value="James Lee Community Center">James Lee Community Center</option>';
strHTML += '<option value="Mclean Community Ctr">Mclean Community Ctr</option>';
strHTML += '<option value="Mott Community Center">Mott Community Center</option>';
strHTML += '<option value="Pinn Community Center">Pinn Community Center</option>';
strHTML += '<option value="Providence Community Center">Providence Community Center</option>';
strHTML += '<option value="Reston Community Center">Reston Community Center</option>';
strHTML += '<option value="Southgate Community Center">Southgate Community Center</option>';
strHTML += '<option value="Tj Community Center">Tj Community Center</option>';
strHTML += '<option value="Vienna Community Center">Vienna Community Center</option>';
strHTML += '</optgroup><optgroup label="DC">';
strHTML += '<option value="Air & Space Museum">Air & Space Museum</option>';
strHTML += '<option value="American Art Museum">American Art Museum</option>';
strHTML += '<option value="Arthur M Sackler Gallery">Arthur M Sackler Gallery</option>';
strHTML += '<option value="Bureau Of Engraving">Bureau Of Engraving</option>';
strHTML += '<option value="Capital One Arena">Capital One Arena</option>';
strHTML += '<option value="Dar Constitution Hall">Dar Constitution Hall</option>';
strHTML += '<option value="Discovery Theatre">Discovery Theatre</option>';
strHTML += '<option value="Fdr Monument">Fdr Monument</option>';
strHTML += '<option value="Federal Reserve Building">Federal Reserve Building</option>';
strHTML += '<option value="Folger Theatre">Folger Theatre</option>';
strHTML += '<option value="Fords Theatre">Fords Theatre</option>';
strHTML += '<option value="Gala Theater">Gala Theater</option>';
strHTML += '<option value="Gang Plank Marina">Gang Plank Marina</option>';
strHTML += '<option value="Georgetown University">Georgetown University</option>';
strHTML += '<option value="Gwu Lisner Auditorium">Gwu Lisner Auditorium</option>';
strHTML += '<option value="Hains Point">Hains Point</option>';
strHTML += '<option value="Harman CenterSidney Harman Hall">Harman Center :  Sidney Harman Hall</option>';
strHTML += '<option value="Hirschorn Museum">Hirschorn Museum</option>';
strHTML += '<option value="Howard University">Howard University</option>';
strHTML += '<option value="Jefferson Memorial">Jefferson Memorial</option>';
strHTML += '<option value="Kennedy Center">Kennedy Center</option>';
strHTML += '<option value="Lansburgh Theatre">Lansburgh Theatre</option>';
strHTML += '<option value="Library Of Congress">Library Of Congress</option>';
strHTML += '<option value="Lincoln Memorial">Lincoln Memorial</option>';
strHTML += '<option value="Lisner Auditorium">Lisner Auditorium</option>';
strHTML += '<option value="National Arboretum">National Arboretum</option>';
strHTML += '<option value="National Archives">National Archives</option>';
strHTML += '<option value="National Building Museum">National Building Museum</option>';
strHTML += '<option value="National Cathedral School">National Cathedral School</option>';
strHTML += '<option value="National Gallery Of Art">National Gallery Of Art</option>';
strHTML += '<option value="National Geographic Museum">National Geographic Museum</option>';
strHTML += '<option value="National Law Enforcement Museum">National Law Enforcement Museum</option>';
strHTML += '<option value="National Museum Of African American History">National Museum Of African American History</option>';
strHTML += '<option value="National Museum Of African Art">National Museum Of African Art</option>';
strHTML += '<option value="National Museum Of American History">National Museum Of American History</option>';
strHTML += '<option value="National Museum Of Natural History">National Museum Of Natural History</option>';
strHTML += '<option value="National Museum Of The American Indian">National Museum Of The American Indian</option>';
strHTML += '<option value="National Postal Museum">National Postal Museum</option>';
strHTML += '<option value="National Zoo">National Zoo</option>';
strHTML += '<option value="NBC 4 Studio">NBC 4 Studio</option>';
strHTML += '<option value="Newseum">Newseum</option>';
strHTML += '<option value="Portrait Gallery">Portrait Gallery</option>';
strHTML += '<option value="Puppet Playhouse">Puppet Playhouse</option>';
strHTML += '<option value="Shakespeare Theatre">Shakespeare Theatre</option>';
strHTML += '<option value="Sydney Harmon Hall">Sydney Harmon Hall</option>';
strHTML += '<option value="The Phillips Collection">The Phillips Collection</option>';
strHTML += '<option value="Theater Alliance">Theater Alliance</option>';
strHTML += '<option value="United States Botanic Gardens">United States Botanic Gardens</option>';
strHTML += '<option value="United States Holocaust Memorial Museum">United States Holocaust Memorial Museum</option>';
strHTML += '<option value="Us Capitol">Us Capitol</option>';
strHTML += '<option value="Us Supreme Court">Us Supreme Court</option>';
strHTML += '<option value="Washington Convention Center">Washington Convention Center</option>';
strHTML += '<option value="Washington Monument">Washington Monument</option>';
strHTML += '<option value="Washington Post">Washington Post</option>';
strHTML += '<option value="Washington Youth Garden">Washington Youth Garden</option>';
strHTML += '<option value="White House">White House</option>';
strHTML += '<option value="World War II Memorial">World War II Memorial</option>';
strHTML += '</optgroup><optgroup label="Elementary">';
strHTML += '<option value="Aldrin ES">Aldrin ES</option>';
strHTML += '<option value="Annandale Terrace ES">Annandale Terrace ES</option>';
strHTML += '<option value="Armstrong ES">Armstrong ES</option>';
strHTML += '<option value="Baileys ES">Baileys ES</option>';
strHTML += '<option value="Baileys Upper ES">Baileys Upper ES</option>';
strHTML += '<option value="Beech Tree ES">Beech Tree ES</option>';
strHTML += '<option value="Belle View ES">Belle View ES</option>';
strHTML += '<option value="Belvedere ES">Belvedere ES</option>';
strHTML += '<option value="Bonnie Brae ES">Bonnie Brae ES</option>';
strHTML += '<option value="Braddock ES">Braddock ES</option>';
strHTML += '<option value="Bren Mar Park ES">Bren Mar Park ES</option>';
strHTML += '<option value="Brookfield ES">Brookfield ES</option>';
strHTML += '<option value="Bucknell ES">Bucknell ES</option>';
strHTML += '<option value="Bull Run ES">Bull Run ES</option>';
strHTML += '<option value="Bush Hill ES">Bush Hill ES</option>';
strHTML += '<option value="Camelot ES">Camelot ES</option>';
strHTML += '<option value="Cameron ES">Cameron ES</option>';
strHTML += '<option value="Canterbury Woods ES">Canterbury Woods ES</option>';
strHTML += '<option value="Cardinal Forest ES">Cardinal Forest ES</option>';
strHTML += '<option value="Centre Ridge ES">Centre Ridge ES</option>';
strHTML += '<option value="Centreville ES">Centreville ES</option>';
strHTML += '<option value="Cherry Run ES">Cherry Run ES</option>';
strHTML += '<option value="Chesterbrook ES">Chesterbrook ES</option>';
strHTML += '<option value="Churchill Road ES">Churchill Road ES</option>';
strHTML += '<option value="Clearview ES">Clearview ES</option>';
strHTML += '<option value="Clermont ES">Clermont ES</option>';
strHTML += '<option value="Coates ES">Coates ES</option>';
strHTML += '<option value="Colin L. Powell ES">Colin L. Powell ES</option>';
strHTML += '<option value="Colin Powell ES">Colin Powell ES</option>';
strHTML += '<option value="Columbia ES">Columbia ES</option>';
strHTML += '<option value="Colvin Run ES">Colvin Run ES</option>';
strHTML += '<option value="Crestwood ES">Crestwood ES</option>';
strHTML += '<option value="Crossfield ES">Crossfield ES</option>';
strHTML += '<option value="Cub Run ES">Cub Run ES</option>';
strHTML += '<option value="Cunningham Park ES">Cunningham Park ES</option>';
strHTML += '<option value="Daniels Run ES">Daniels Run ES</option>';
strHTML += '<option value="Deer Park ES">Deer Park ES</option>';
strHTML += '<option value="Dogwood ES">Dogwood ES</option>';
strHTML += '<option value="Dranesville ES">Dranesville ES</option>';
strHTML += '<option value="Eagle View ES">Eagle View ES</option>';
strHTML += '<option value="Fairfax Villa ES">Fairfax Villa ES</option>';
strHTML += '<option value="Fairhill ES">Fairhill ES</option>';
strHTML += '<option value="Fairview ES">Fairview ES</option>';
strHTML += '<option value="Flint Hill ES">Flint Hill ES</option>';
strHTML += '<option value="Floris ES">Floris ES</option>';
strHTML += '<option value="Forest Edge ES">Forest Edge ES</option>';
strHTML += '<option value="Forestdale ES">Forestdale ES</option>';
strHTML += '<option value="Forestville ES">Forestville ES</option>';
strHTML += '<option value="Fort Belvoir ES">Fort Belvoir ES</option>';
strHTML += '<option value="Fort Belvoir Upper ES">Fort Belvoir Upper ES</option>';
strHTML += '<option value="Fort Hunt ES">Fort Hunt ES</option>';
strHTML += '<option value="Fox Mill ES">Fox Mill ES</option>';
strHTML += '<option value="Franconia ES">Franconia ES</option>';
strHTML += '<option value="Franklin Sherman ES">Franklin Sherman ES</option>';
strHTML += '<option value="Freedom Hill ES">Freedom Hill ES</option>';
strHTML += '<option value="Garfield ES">Garfield ES</option>';
strHTML += '<option value="Glen Forest ES">Glen Forest ES</option>';
strHTML += '<option value="Graham Road ES">Graham Road ES</option>';
strHTML += '<option value="Great Falls ES">Great Falls ES</option>';
strHTML += '<option value="Greenbriar East ES">Greenbriar East ES</option>';
strHTML += '<option value="Greenbriar West ES">Greenbriar West ES</option>';
strHTML += '<option value="Groveton ES">Groveton ES</option>';
strHTML += '<option value="Gunston ES">Gunston ES</option>';
strHTML += '<option value="Halley ES">Halley ES</option>';
strHTML += '<option value="Haycock ES">Haycock ES</option>';
strHTML += '<option value="Hayfield ES">Hayfield ES</option>';
strHTML += '<option value="Herndon ES">Herndon ES</option>';
strHTML += '<option value="Hollin Meadows ES">Hollin Meadows ES</option>';
strHTML += '<option value="Hunt Valley ES">Hunt Valley ES</option>';
strHTML += '<option value="Hunters Woods ES">Hunters Woods ES</option>';
strHTML += '<option value="Hutchison ES">Hutchison ES</option>';
strHTML += '<option value="Hybla Valley ES">Hybla Valley ES</option>';
strHTML += '<option value="Island Creek ES">Island Creek ES</option>';
strHTML += '<option value="Keene Mill ES">Keene Mill ES</option>';
strHTML += '<option value="Kent Gardens ES">Kent Gardens ES</option>';
strHTML += '<option value="Kings Glen ES">Kings Glen ES</option>';
strHTML += '<option value="Kings Park ES">Kings Park ES</option>';
strHTML += '<option value="Lake Anne ES">Lake Anne ES</option>';
strHTML += '<option value="Lane ES">Lane ES</option>';
strHTML += '<option value="Laurel Hill ES">Laurel Hill ES</option>';
strHTML += '<option value="Laurel Ridge ES">Laurel Ridge ES</option>';
strHTML += '<option value="Lees Corner ES">Lees Corner ES</option>';
strHTML += '<option value="Lemon Road ES">Lemon Road ES</option>';
strHTML += '<option value="Little Run ES">Little Run ES</option>';
strHTML += '<option value="London Towne ES">London Towne ES</option>';
strHTML += '<option value="Lorton Station ES">Lorton Station ES</option>';
strHTML += '<option value="Louise Archer ES">Louise Archer ES</option>';
strHTML += '<option value="Lynbrook ES">Lynbrook ES</option>';
strHTML += '<option value="Mantua ES">Mantua ES</option>';
strHTML += '<option value="Marshall Road ES">Marshall Road ES</option>';
strHTML += '<option value="Mason Crest ES">Mason Crest ES</option>';
strHTML += '<option value="Mcnair ES">Mcnair ES</option>';
strHTML += '<option value="Mosby Woods ES">Mosby Woods ES</option>';
strHTML += '<option value="Mount Eagle ES">Mount Eagle ES</option>';
strHTML += '<option value="Mount Vernon Woods ES">Mount Vernon Woods ES</option>';
strHTML += '<option value="Mount Vernontate ES">Mount Vernontate ES</option>';
strHTML += '<option value="Navy ES">Navy ES</option>';
strHTML += '<option value="Newington Forest ES">Newington Forest ES</option>';
strHTML += '<option value="North Springfield ES">North Springfield ES</option>';
strHTML += '<option value="Oak Hill ES">Oak Hill ES</option>';
strHTML += '<option value="Oak View ES">Oak View ES</option>';
strHTML += '<option value="Oakton ES">Oakton ES</option>';
strHTML += '<option value="Olde Creek ES">Olde Creek ES</option>';
strHTML += '<option value="Orange Hunt ES">Orange Hunt ES</option>';
strHTML += '<option value="Parklawn ES">Parklawn ES</option>';
strHTML += '<option value="Pine Spring ES">Pine Spring ES</option>';
strHTML += '<option value="Poplar Tree ES">Poplar Tree ES</option>';
strHTML += '<option value="Providence ES">Providence ES</option>';
strHTML += '<option value="Ravensworth ES">Ravensworth ES</option>';
strHTML += '<option value="Riverside ES">Riverside ES</option>';
strHTML += '<option value="Rolling Valley ES">Rolling Valley ES</option>';
strHTML += '<option value="Rose Hill ES">Rose Hill ES</option>';
strHTML += '<option value="Sangster ES">Sangster ES</option>';
strHTML += '<option value="Saratoga ES">Saratoga ES</option>';
strHTML += '<option value="Shrevewood ES">Shrevewood ES</option>';
strHTML += '<option value="Silverbrook ES">Silverbrook ES</option>';
strHTML += '<option value="Sleepy Hollow ES">Sleepy Hollow ES</option>';
strHTML += '<option value="Spring Hill ES">Spring Hill ES</option>';
strHTML += '<option value="Springfieldtates ES">Springfieldtates ES</option>';
strHTML += '<option value="Stenwood ES">Stenwood ES</option>';
strHTML += '<option value="Stratford Landing ES">Stratford Landing ES</option>';
strHTML += '<option value="Sunrise Valley ES">Sunrise Valley ES</option>';
strHTML += '<option value="Terra Centre ES">Terra Centre ES</option>';
strHTML += '<option value="Terraset ES">Terraset ES</option>';
strHTML += '<option value="Timber Lane ES">Timber Lane ES</option>';
strHTML += '<option value="Union Mill ES">Union Mill ES</option>';
strHTML += '<option value="Vienna ES">Vienna ES</option>';
strHTML += '<option value="Virginia Run ES">Virginia Run ES</option>';
strHTML += '<option value="Wakefield Forest ES">Wakefield Forest ES</option>';
strHTML += '<option value="Waples Mill ES">Waples Mill ES</option>';
strHTML += '<option value="Washington Mill ES">Washington Mill ES</option>';
strHTML += '<option value="Waynewood ES">Waynewood ES</option>';
strHTML += '<option value="West Springfield ES">West Springfield ES</option>';
strHTML += '<option value="Westbriar ES">Westbriar ES</option>';
strHTML += '<option value="Westgate ES">Westgate ES</option>';
strHTML += '<option value="Westlawn ES">Westlawn ES</option>';
strHTML += '<option value="Weyanoke ES">Weyanoke ES</option>';
strHTML += '<option value="White Oaks ES">White Oaks ES</option>';
strHTML += '<option value="Willow Springs ES">Willow Springs ES</option>';
strHTML += '<option value="Wolftrap ES">Wolftrap ES</option>';
strHTML += '<option value="Woodburn ES">Woodburn ES</option>';
strHTML += '<option value="Woodlawn ES">Woodlawn ES</option>';
strHTML += '<option value="Woodley Hills ES">Woodley Hills ES</option>';
strHTML += '</optgroup><optgroup label="Farm">';
strHTML += '<option value="Accokeek Colonial Farm">Accokeek Colonial Farm</option>';
strHTML += '<option value="Amazing Farm Fun">Amazing Farm Fun</option>';
strHTML += '<option value="Arcadia Farm">Arcadia Farm</option>';
strHTML += '<option value="Ballentine Farm">Ballentine Farm</option>';
strHTML += '<option value="Cows N Corn Farm">Cows N Corn Farm</option>';
strHTML += '<option value="Cox Farm">Cox Farm</option>';
strHTML += '<option value="Great Country Farms">Great Country Farms</option>';
strHTML += '<option value="Hartland Farm And Orchard">Hartland Farm And Orchard</option>';
strHTML += '<option value="Kidwell Farms">Kidwell Farms</option>';
strHTML += '<option value="Miller Farms">Miller Farms</option>';
strHTML += '<option value="Oxon Hill Farm">Oxon Hill Farm</option>';
strHTML += '<option value="Panorama Farm">Panorama Farm</option>';
strHTML += '<option value="Potomac Vegetable Farm">Potomac Vegetable Farm</option>';
strHTML += '<option value="Shlagel Farms">Shlagel Farms</option>';
strHTML += '<option value="Ticonderoga Farm">Ticonderoga Farm</option>';
strHTML += '<option value="Wayside Farm">Wayside Farm</option>';
strHTML += '<option value="Whitehall Farm">Whitehall Farm</option>';
strHTML += '</optgroup><optgroup label="GMU">'
strHTML += '<option value="Center For The Arts">Center For The Arts</option>';
strHTML += '<option value="Eagle Bank Arena">Eagle Bank Arena</option>';
strHTML += '<option value="Patriot Center">Patriot Center</option>';
strHTML += '<option value="The Edge">The Edge</option>';
strHTML += '</optgroup><optgroup label="High">';
strHTML += '<option value="Annandale HS">Annandale HS</option>';
strHTML += '<option value="Arundel HS">Arundel HS</option>';
strHTML += '<option value="Atlee HS">Atlee HS</option>';
strHTML += '<option value="Battlefield HS">Battlefield HS</option>';
strHTML += '<option value="Bishop Ireton HS">Bishop Ireton HS</option>';
strHTML += '<option value="Bishop Mcnamara HS">Bishop Mcnamara HS</option>';
strHTML += '<option value="Boonsboro HS">Boonsboro HS</option>';
strHTML += '<option value="Brentsville District HS">Brentsville District HS</option>';
strHTML += '<option value="Briar Woods HS">Briar Woods HS</option>';
strHTML += '<option value="Broad Run HS">Broad Run HS</option>';
strHTML += '<option value="Brooke Point HS">Brooke Point HS</option>';
strHTML += '<option value="Bryant Alt HS">Bryant Alt HS</option>';
strHTML += '<option value="Centreville HS">Centreville HS</option>';
strHTML += '<option value="Chantilly HS">Chantilly HS</option>';
strHTML += '<option value="Charles J. Colgan Sr. HS">Charles J. Colgan Sr. HS</option>';
strHTML += '<option value="Colonial Forge HS">Colonial Forge HS</option>';
strHTML += '<option value="Culpeper County HS">Culpeper County HS</option>';
strHTML += '<option value="Damascus HS">Damascus HS</option>';
strHTML += '<option value="Dominion HS">Dominion HS</option>';
strHTML += '<option value="Dunbar HS">Dunbar HS</option>';
strHTML += '<option value="Dundalk HS">Dundalk HS</option>';
strHTML += '<option value="Eastern View HS">Eastern View HS</option>';
strHTML += '<option value="Easton HS">Easton HS</option>';
strHTML += '<option value="Edison HS">Edison HS</option>';
strHTML += '<option value="Episcopal HS">Episcopal HS</option>';
strHTML += '<option value="Fairfax HS">Fairfax HS</option>';
strHTML += '<option value="Falls Church HS">Falls Church HS</option>';
strHTML += '<option value="Fauquier HS">Fauquier HS</option>';
strHTML += '<option value="Flint Hill HS">Flint Hill HS</option>';
strHTML += '<option value="Forest Park HS">Forest Park HS</option>';
strHTML += '<option value="Freedom HS (Loudoun)">Freedom HS(Loudoun)</option>';
strHTML += '<option value="Freedom HS (Prince William)">Freedom HS(Prince William)</option>';
strHTML += '<option value="Gar: Field HS">Gar: Field HS</option>';
strHTML += '<option value="George Mason HS">George Mason HS</option>';
strHTML += '<option value="Glen Allen HS">Glen Allen HS</option>';
strHTML += '<option value="Gonzaga College HS">Gonzaga College HS</option>';
strHTML += '<option value="Handley HS">Handley HS</option>';
strHTML += '<option value="Harrisonburg HS">Harrisonburg HS</option>';
strHTML += '<option value="Hayfield Sec HS">Hayfield Sec HS</option>';
strHTML += '<option value="Hd Woodson HS">Hd Woodson HS</option>';
strHTML += '<option value="Heritage HS">Heritage HS</option>';
strHTML += '<option value="Herndon HS">Herndon HS</option>';
strHTML += '<option value="Hylton HS">Hylton HS</option>';
strHTML += '<option value="John Champe HS">John Champe HS</option>';
strHTML += '<option value="Justice HS">Justice HS</option>';
strHTML += '<option value="King George HS">King George HS</option>';
strHTML += '<option value="Lake Braddock Sec HS">Lake Braddock Sec HS</option>';
strHTML += '<option value="Langley HS">Langley HS</option>';
strHTML += '<option value="Lee HS">Lee HS</option>';
strHTML += '<option value="Lee: Davis HS">Lee: Davis HS</option>';
strHTML += '<option value="Leonardtown HS">Leonardtown HS</option>';
strHTML += '<option value="Liberty HS">Liberty HS</option>';
strHTML += '<option value="Loudon Valley HS">Loudon Valley HS</option>';
strHTML += '<option value="Loudoun County HS">Loudoun County HS</option>';
strHTML += '<option value="Loudoun Valley HS">Loudoun Valley HS</option>';
strHTML += '<option value="Madeira HS">Madeira HS</option>';
strHTML += '<option value="Madison HS">Madison HS</option>';
strHTML += '<option value="Magruder HS">Magruder HS</option>';
strHTML += '<option value="Marshall HS">Marshall HS</option>';
strHTML += '<option value="Mcdonough HS">Mcdonough HS</option>';
strHTML += '<option value="Mclean HS">Mclean HS</option>';
strHTML += '<option value="Millbrook HS">Millbrook HS</option>';
strHTML += '<option value="Minnie Howard School">Minnie Howard School</option>';
strHTML += '<option value="Montgomery Blair HS">Montgomery Blair HS</option>';
strHTML += '<option value="Mount Vernon HS">Mount Vernon HS</option>';
strHTML += '<option value="Mountain View HS">Mountain View HS</option>';
strHTML += '<option value="Mountain View Alt HS">Mountain View Alt HS</option>';
strHTML += '<option value="North Stafford HS">North Stafford HS</option>';
strHTML += '<option value="Northwest HS">Northwest HS</option>';
strHTML += '<option value="Oakton HS">Oakton HS</option>';
strHTML += '<option value="Oconnell HS">Oconnell HS</option>';
strHTML += '<option value="Osbourn HS">Osbourn HS</option>';
strHTML += '<option value="Osbourn Park HS">Osbourn Park HS</option>';
strHTML += '<option value="Our Lady Of Good Counsel HS">Our Lady Of Good Counsel HS</option>';
strHTML += '<option value="Park View HS">Park View HS</option>';
strHTML += '<option value="Patriot HS">Patriot HS</option>';
strHTML += '<option value="Patuxent HS">Patuxent HS</option>';
strHTML += '<option value="Paul VI HS">Paul VI HS</option>';
strHTML += '<option value="Poolesville HS (MD)">Poolesville HS (MD)</option>';
strHTML += '<option value="Potomac HS (Dumfries)">Potomac HS (Dumfries)</option>';
strHTML += '<option value="Potomac Falls HS (Sterling)">Potomac Falls HS (Sterling)</option>';
strHTML += '<option value="Riverbend HS">Riverbend HS</option>';
strHTML += '<option value="Riverside HS">Riverside HS</option>';
strHTML += '<option value="Robinson Sec HS">Robinson Sec HS</option>';
strHTML += '<option value="Rock Ridge HS">Rock Ridge HS</option>';
strHTML += '<option value="Roosevelt HS">Roosevelt HS</option>';
strHTML += '<option value="Sidwell Friends HS">Sidwell Friends HS</option>';
strHTML += '<option value="South County HS">South County HS</option>';
strHTML += '<option value="South Lakes HS">South Lakes HS</option>';
strHTML += '<option value="Spotsylvania HS">Spotsylvania HS</option>';
strHTML += '<option value="St John Paul The Great HS">St John Paul The Great HS</option>';
strHTML += '<option value="St. Johns College HS">St. Johns College HS</option>';
strHTML += '<option value="Stafford HS">Stafford HS</option>';
strHTML += '<option value="Stonebridge HS">Stonebridge HS</option>';
strHTML += '<option value="Stonewall Jackson HS">Stonewall Jackson HS</option>';
strHTML += '<option value="TC Williams HS">TC Williams HS</option>';
strHTML += '<option value="TJHSST">TJHSST</option>';
strHTML += '<option value="Tuscarora HS">Tuscarora HS</option>';
strHTML += '<option value="Urbana HS">Urbana HS</option>';
strHTML += '<option value="Wakefield HS">Wakefield HS</option>';
strHTML += '<option value="Washington: Lee HS">Washington: Lee HS</option>';
strHTML += '<option value="West Potomac HS">West Potomac HS</option>';
strHTML += '<option value="West Springfield HS">West Springfield HS</option>';
strHTML += '<option value="Westfield HS">Westfield HS</option>';
strHTML += '<option value="Woodbridge HS">Woodbridge HS</option>';
strHTML += '<option value="Woodgrove HS">Woodgrove HS</option>';
strHTML += '<option value="Woodson HS">Woodson HS</option>';
strHTML += '<option value="Yorktown HS">Yorktown HS</option>';
strHTML += '</optgroup><optgroup label="Middle">';
strHTML += '<option value="Alice Deal MS">Alice Deal MS</option>';
strHTML += '<option value="Carl Sandburg MS">Carl Sandburg MS</option>';
strHTML += '<option value="Carson MS">Carson MS</option>';
strHTML += '<option value="Cooper MS">Cooper MS</option>';
strHTML += '<option value="Francis Hammond MS">Francis Hammond MS</option>';
strHTML += '<option value="Franklin MS">Franklin MS</option>';
strHTML += '<option value="Frost MS">Frost MS</option>';
strHTML += '<option value="Glasgow MS">Glasgow MS</option>';
strHTML += '<option value="Herndon MS">Herndon MS</option>';
strHTML += '<option value="Holmes MS">Holmes MS</option>';
strHTML += '<option value="Hughes MS">Hughes MS</option>';
strHTML += '<option value="Irving MS">Irving MS</option>';
strHTML += '<option value="Kenmore MS">Kenmore MS</option>';
strHTML += '<option value="Kenmore School MS">Kenmore School MS</option>';
strHTML += '<option value="Key MS">Key MS</option>';
strHTML += '<option value="Kilmer MS">Kilmer MS</option>';
strHTML += '<option value="Lanier MS">Lanier MS</option>';
strHTML += '<option value="Liberty MS">Liberty MS</option>';
strHTML += '<option value="Longfellow MS">Longfellow MS</option>';
strHTML += '<option value="Luther Jackson MS">Luther Jackson MS</option>';
strHTML += '<option value="Mary Ellen Henderson MS">Mary Ellen Henderson MS</option>';
strHTML += '<option value="Poe MS">Poe MS</option>';
strHTML += '<option value="Rocky Run MS">Rocky Run MS</option>';
strHTML += '<option value="Sandburg MS">Sandburg MS</option>';
strHTML += '<option value="South County MS">South County MS</option>';
strHTML += '<option value="Stone MS">Stone MS</option>';
strHTML += '<option value="Thomas Jefferson MS">Thomas Jefferson MS</option>';
strHTML += '<option value="Thoreau MS">Thoreau MS</option>';
strHTML += '<option value="Twain MS">Twain MS</option>';
strHTML += '<option value="Whitman MS">Whitman MS</option>';
strHTML += '</optgroup>';
strHTML += '<option value="Museum: Air & Space :  Udvar Center">Museum: Air & Space :  Udvar Center</option>';
strHTML += '<option value="Museum: Alexandria Archeology">Museum: Alexandria Archeology</option>';
strHTML += '<option value="Museum: B & O Train">Museum: B & O Train</option>';
strHTML += '<option value="Museum: Carlyle House Apothecary">Museum: Carlyle House Apothecary</option>';
strHTML += '<option value="Museum: Glenstone">Museum: Glenstone</option>';
strHTML += '<option value="Museum: Heritage Farm">Museum: Heritage Farm</option>';
strHTML += '<option value="Museum: National Cryptologic">Museum: National Cryptologic</option>';
strHTML += '<option value="Museum: National Electronics">Museum: National Electronics</option>';
strHTML += '<option value="Museum: National Museum Of The Marine Corps">Museum: National Museum Of The Marine Corps</option>';
strHTML += '<option value="Nova :  Alexandria">Nova :  Alexandria</option>';
strHTML += '<option value="Nova :  Annandale">Nova :  Annandale</option>';
strHTML += '<option value="Nova :  Loudoun">Nova :  Loudoun</option>';
strHTML += '<option value="Nova :  Manassas">Nova :  Manassas</option>';
strHTML += '<option value="Nova :  Springfield Medical Campus">Nova :  Springfield Medical Campus</option>';
strHTML += '<option value="Other: Adventure Links">Other: Adventure Links</option>';
strHTML += '<option value="Other: Alan Leis Instr. Center">Other: Alan Leis Instr. Center</option>';
strHTML += '<option value="Other: American University">Other: American University</option>';
strHTML += '<option value="Other: Amf Bowling">Other: Amf Bowling</option>';
strHTML += '<option value="Other: Arlington National Cemetary">Other: Arlington National Cemetary</option>';
strHTML += '<option value="Other: Artechouse">Other: Artechouse</option>';
strHTML += '<option value="Other: Ashby Pond Conservatory Site">Other: Ashby Pond Conservatory Site</option>';
strHTML += '<option value="Other: Beehive Indoor Playground">Other: Beehive Indoor Playground</option>';
strHTML += '<option value="Other: Bellmont Bay Harbor">Other: Bellmont Bay Harbor</option>';
strHTML += '<option value="Other: Billy Beez">Other: Billy Beez</option>';
strHTML += '<option value="Other: Bowl America">Other: Bowl America</option>';
strHTML += '<option value="Other: Brightline Interactive">Other: Brightline Interactive</option>';
strHTML += '<option value="Other: Burke Garden Center">Other: Burke Garden Center</option>';
strHTML += '<option value="Other: Camp Crowell">Other: Camp Crowell</option>';
strHTML += '<option value="Other: Cedar Ridge Clcp">Other: Cedar Ridge Clcp</option>';
strHTML += '<option value="Other: Centreville Baptist Church">Other: Centreville Baptist Church</option>';
strHTML += '<option value="Other: Centrewood Plaza">Other: Centrewood Plaza</option>';
strHTML += '<option value="Other: Cherry Hill Farmhouse">Other: Cherry Hill Farmhouse</option>';
strHTML += '<option value="Other: Chesapeake Bay Foundation">Other: Chesapeake Bay Foundation</option>';
strHTML += '<option value="Other: Children Science Center">Other: Children Science Center</option>';
strHTML += '<option value="Other: Cia">Other: Cia</option>';
strHTML += '<option value="Other: Circuit Court Of Fairfax County">Other: Circuit Court Of Fairfax County</option>';
strHTML += '<option value="Other: Clay Cafe">Other: Clay Cafe</option>';
strHTML += '<option value="Other: Clearwater Nature Center">Other: Clearwater Nature Center</option>';
strHTML += '<option value="Other: Cole Sewage Treatment Plant">Other: Cole Sewage Treatment Plant</option>';
strHTML += '<option value="Other: Colonnade Shopping Center">Other: Colonnade Shopping Center</option>';
strHTML += '<option value="Other: Colvin Run Mill">Other: Colvin Run Mill</option>';
strHTML += '<option value="Other: Criminal Justice Academy">Other: Criminal Justice Academy</option>';
strHTML += '<option value="Other: Custom Ink">Other: Custom Ink</option>';
strHTML += '<option value="Other: Dave & Buster">Other: Dave & Buster</option>';
strHTML += '<option value="Other: Del Ray Cafe">Other: Del Ray Cafe</option>';
strHTML += '<option value="Other: Dogfish Head Alehouse">Other: Dogfish Head Alehouse</option>';
strHTML += '<option value="Other: Dominion Power">Other: Dominion Power</option>';
strHTML += '<option value="Other: Dulles Airport">Other: Dulles Airport</option>';
strHTML += '<option value="Other: Dulles Town Center">Other: Dulles Town Center</option>';
strHTML += '<option value="Other: Dyke Marsh Wildlife Preserve">Other: Dyke Marsh Wildlife Preserve</option>';
strHTML += '<option value="Other: Elks Club Of Fairfax">Other: Elks Club Of Fairfax</option>';
strHTML += '<option value="Other: Emmanuel Baptist Church">Other: Emmanuel Baptist Church</option>';
strHTML += '<option value="Other: Entertainment & Sports Arena">Other: Entertainment & Sports Arena</option>';
strHTML += '<option value="Other: Escape Room">Other: Escape Room</option>';
strHTML += '<option value="Other: Evergreen Sports Complex">Other: Evergreen Sports Complex</option>';
strHTML += '<option value="Other: Fair Oaks Mall">Other: Fair Oaks Mall</option>';
strHTML += '<option value="Other: Fairfax County Circuit Court">Other: Fairfax County Circuit Court</option>';
strHTML += '<option value="Other: Fairfax County Solid Waste Management I-95">Other: Fairfax County Solid Waste Management I-95</option>';
strHTML += '<option value="Other: Fairfax Recycling :  Disposal Facility">Other: Fairfax Recycling :  Disposal Facility</option>';
strHTML += '<option value="Other: Fairfax Ridge">Other: Fairfax Ridge</option>';
strHTML += '<option value="Other: Fedex Field">Other: Fedex Field</option>';
strHTML += '<option value="Other: Finance Park">Other: Finance Park</option>';
strHTML += '<option value="Other: Fort Belvoir Bowling Centr">Other: Fort Belvoir Bowling Centr</option>';
strHTML += '<option value="Other: Franconia Moose Lodge">Other: Franconia Moose Lodge</option>';
strHTML += '<option value="Other: Gallaudet University">Other: Gallaudet University</option>';
strHTML += '<option value="Other: Gatehouse Administrative Center">Other: Gatehouse Administrative Center</option>';
strHTML += '<option value="Other: Gaylord National Resort">Other: Gaylord National Resort</option>';
strHTML += '<option value="Other: Giant Food">Other: Giant Food</option>';
strHTML += '<option value="Other: Green Acres">Other: Green Acres</option>';
strHTML += '<option value="Other: Griffith Water Quality Plant">Other: Griffith Water Quality Plant</option>';
strHTML += '<option value="Other: Gunston Hall">Other: Gunston Hall</option>';
strHTML += '<option value="Other: Gunston Plaza">Other: Gunston Plaza</option>';
strHTML += '<option value="Other: Herndon Clcp">Other: Herndon Clcp</option>';
strHTML += '<option value="Other: Herndon Senior Center">Other: Herndon Senior Center</option>';
strHTML += '<option value="Other: Hidden Oaks Nature Center">Other: Hidden Oaks Nature Center</option>';
strHTML += '<option value="Other: Hidden Pond">Other: Hidden Pond</option>';
strHTML += '<option value="Other: Holiday Inn Express">Other: Holiday Inn Express</option>';
strHTML += '<option value="Other: Home Depot">Other: Home Depot</option>';
strHTML += '<option value="Other: Homeward Trails">Other: Homeward Trails</option>';
strHTML += '<option value="Other: Hood College">Other: Hood College</option>';
strHTML += '<option value="Other: Hyatt Regency Baltimore">Other: Hyatt Regency Baltimore</option>';
strHTML += '<option value="Other: IHOP">Other: IHOP</option>';
strHTML += '<option value="Other: Innerquest">Other: Innerquest</option>';
strHTML += '<option value="Other: Inova Fairfax Hospital">Other: Inova Fairfax Hospital</option>';
strHTML += '<option value="Other: Jerome Ford Nature Center">Other: Jerome Ford Nature Center</option>';
strHTML += '<option value="Other: Johns Hopkins University">Other: Johns Hopkins University</option>';
strHTML += '<option value="Other: Joint Base Andrews, Clinton Md">Other: Joint Base Andrews, Clinton Md</option>';
strHTML += '<option value="Other: JP Morgan Chase Building">Other: JP Morgan Chase Building</option>';
strHTML += '<option value="Other: Kid Junction">Other: Kid Junction</option>';
strHTML += '<option value="Other: Kings Dominion">Other: Kings Dominion</option>';
strHTML += '<option value="Other: Kinsley Commons Clcp">Other: Kinsley Commons Clcp</option>';
strHTML += '<option value="Other: Laser Quest">Other: Laser Quest</option>';
strHTML += '<option value="Other: Laurel Grove School">Other: Laurel Grove School</option>';
strHTML += '<option value="Other: Luray Caverns">Other: Luray Caverns</option>';
strHTML += '<option value="Other: Manassas Battlefield">Other: Manassas Battlefield</option>';
strHTML += '<option value="Other: Marriot">Other: Marriot</option>';
strHTML += '<option value="Other: Martha Washington Library">Other: Martha Washington Library</option>';
strHTML += '<option value="Other: Mary Washington College">Other: Mary Washington College</option>';
strHTML += '<option value="Other: Maryland Science Center">Other: Maryland Science Center</option>';
strHTML += '<option value="Other: Marymount University">Other: Marymount University</option>';
strHTML += '<option value="Other: Mclean Project For The Arts">Other: Mclean Project For The Arts</option>';
strHTML += '<option value="Other: Meadowlark Botanical Gardens">Other: Meadowlark Botanical Gardens</option>';
strHTML += '<option value="Other: Medieval Times">Other: Medieval Times</option>';
strHTML += '<option value="Other: Monster Mini Golf">Other: Monster Mini Golf</option>';
strHTML += '<option value="Other: Mount Saint Marys University">Other: Mount Saint Marys University</option>';
strHTML += '<option value="Other: Nancy F. Sprague Ctr">Other: Nancy F. Sprague Ctr</option>';
strHTML += '<option value="Other: Nasa Goddard">Other: Nasa Goddard</option>';
strHTML += '<option value="Other: National Aquarium">Other: National Aquarium</option>';
strHTML += '<option value="Other: National Geospatial Intelligence Agency">Other: National Geospatial Intelligence Agency</option>';
strHTML += '<option value="Other: National Harbor">Other: National Harbor</option>';
strHTML += '<option value="Other: National Inventors Hall Of Fame">Other: National Inventors Hall Of Fame</option>';
strHTML += '<option value="Other: National Reconnaissance Office">Other: National Reconnaissance Office</option>';
strHTML += '<option value="Other: Navy Federal Credit Union">Other: Navy Federal Credit Union</option>';
strHTML += '<option value="Other: Navy: Marcine Corps Memorial Stadium">Other: Navy: Marcine Corps Memorial Stadium</option>';
strHTML += '<option value="Other: New Market Battlefield">Other: New Market Battlefield</option>';
strHTML += '<option value="Other: Norman Cole Pollution Control Plant">Other: Norman Cole Pollution Control Plant</option>';
strHTML += '<option value="Other: Northrop Grumman :  Mclean, Va">Other: Northrop Grumman :  Mclean, Va</option>';
strHTML += '<option value="Other: Nysmith School For The Gifted">Other: Nysmith School For The Gifted</option>';
strHTML += '<option value="Other: Omni Shorham Hotel">Other: Omni Shorham Hotel</option>';
strHTML += '<option value="Other: Pennino Building">Other: Pennino Building</option>';
strHTML += '<option value="Other: Pfitzner Stadium">Other: Pfitzner Stadium</option>';
strHTML += '<option value="Other: Pirates Cove Waterpark">Other: Pirates Cove Waterpark</option>';
strHTML += '<option value="Other: Planetarium">Other: Planetarium</option>';
strHTML += '<option value="Other: Pohick Regional Library">Other: Pohick Regional Library</option>';
strHTML += '<option value="Other: Potomac School">Other: Potomac School</option>';
strHTML += '<option value="Other: President Lincolns Cottage">Other: President Lincolns Cottage</option>';
strHTML += '<option value="Other: Prince Georges Sports Complex & Learning Ctr">Other: Prince Georges Sports Complex & Learning Ctr</option>';
strHTML += '<option value="Other: Prince William Co Fairgrounds">Other: Prince William Co Fairgrounds</option>';
strHTML += '<option value="Other: Prince William Co Sports Complex">Other: Prince William Co Sports Complex</option>';
strHTML += '<option value="Other: Pump It Up">Other: Pump It Up</option>';
strHTML += '<option value="Other: Quest Diagnostic">Other: Quest Diagnostic</option>';
strHTML += '<option value="Other: Reagan National Airport">Other: Reagan National Airport</option>';
strHTML += '<option value="Other: Reston Farm Market">Other: Reston Farm Market</option>';
strHTML += '<option value="Other: Reston Sheraton Hotel">Other: Reston Sheraton Hotel</option>';
strHTML += '<option value="Other: Reston Wiehle Metro Station">Other: Reston Wiehle Metro Station</option>';
strHTML += '<option value="Other: Rock The Spectrum Gym">Other: Rock The Spectrum Gym</option>';
strHTML += '<option value="Other: Roer Zoofari">Other: Roer Zoofari</option>';
strHTML += '<option value="Other: Safeway">Other: Safeway</option>';
strHTML += '<option value="Other: Scotts Run Nature Preserve">Other: Scotts Run Nature Preserve</option>';
strHTML += '<option value="Other: Shady Grove University">Other: Shady Grove University</option>';
strHTML += '<option value="Other: Shenandoah University">Other: Shenandoah University</option>';
strHTML += '<option value="Other: Sideburn Center">Other: Sideburn Center</option>';
strHTML += '<option value="Other: Six Flags :  Maryland">Other: Six Flags :  Maryland</option>';
strHTML += '<option value="Other: Skate : N:  Fun Zone">Other: Skate : N:  Fun Zone</option>';
strHTML += '<option value="Other: Skyline Caverns">Other: Skyline Caverns</option>';
strHTML += '<option value="Other: Sportrock Climbing Center">Other: Sportrock Climbing Center</option>';
strHTML += '<option value="Other: Sports Bounce Of Loudoun">Other: Sports Bounce Of Loudoun</option>';
strHTML += '<option value="Other: Sprotrock Climbing Center">Other: Sprotrock Climbing Center</option>';
strHTML += '<option value="Other: Sprout Therapeutic Riding Center">Other: Sprout Therapeutic Riding Center</option>';
strHTML += '<option value="Other: St. James Sports And Wellness Center">Other: St. James Sports And Wellness Center</option>';
strHTML += '<option value="Other: St. Mary Church On Sideburn Road">Other: St. Mary Church On Sideburn Road</option>';
strHTML += '<option value="Other: St. Stephens & St. Agnes School">Other: St. Stephens & St. Agnes School</option>';
strHTML += '<option value="Other: Station 26 :  Edsall Road">Other: Station 26 :  Edsall Road</option>';
strHTML += '<option value="Other: Station 3 :  City Of Fairfax">Other: Station 3 :  City Of Fairfax</option>';
strHTML += '<option value="Other: Sully District Police Station">Other: Sully District Police Station</option>';
strHTML += '<option value="Other: Sully Plantation">Other: Sully Plantation</option>';
strHTML += '<option value="Other: Sunrise Assisted Living">Other: Sunrise Assisted Living</option>';
strHTML += '<option value="Other: Thomas Jefferson Library">Other: Thomas Jefferson Library</option>';
strHTML += '<option value="Other: Thompson Wildlife Management Area">Other: Thompson Wildlife Management Area</option>';
strHTML += '<option value="Other: Thrill Zone">Other: Thrill Zone</option>';
strHTML += '<option value="Other: Top Golf">Other: Top Golf</option>';
strHTML += '<option value="Other: Torpedo Factory Art Center">Other: Torpedo Factory Art Center</option>';
strHTML += '<option value="Other: Trinity Christian School">Other: Trinity Christian School</option>';
strHTML += '<option value="Other: Trinity United Methodist Church">Other: Trinity United Methodist Church</option>';
strHTML += '<option value="Other: United States Naval Academy">Other: United States Naval Academy</option>';
strHTML += '<option value="Other: University Of Mary Washington">Other: University Of Mary Washington</option>';
strHTML += '<option value="Other: Uptown Alley">Other: Uptown Alley</option>';
strHTML += '<option value="Other: Vienna Metro Station">Other: Vienna Metro Station</option>';
strHTML += '<option value="Other: Virginia Tech Thinkabit Lab">Other: Virginia Tech Thinkabit Lab</option>';
strHTML += '<option value="Other: Vulcan Quarry">Other: Vulcan Quarry</option>';
strHTML += '<option value="Other: Walker Nature Education Center">Other: Walker Nature Education Center</option>';
strHTML += '<option value="Other: Water Mine">Other: Water Mine</option>';
strHTML += '<option value="Other: Water Treatment Plant">Other: Water Treatment Plant</option>';
strHTML += '<option value="Other: Waterford">Other: Waterford</option>';
strHTML += '<option value="Other: West Springfield District Police Station">Other: West Springfield District Police Station</option>';
strHTML += '<option value="Other: Willow Oaks">Other: Willow Oaks</option>';
strHTML += '<option value="Other: Willston Multiculteral Center">Other: Willston Multiculteral Center</option>';
strHTML += '<option value="Other: Witter Athletic Fields">Other: Witter Athletic Fields</option>';
strHTML += '<option value="Other: Wolf Trap">Other: Wolf Trap</option>';
strHTML += '<option value="Other: Woodland Hill Retirement Home">Other: Woodland Hill Retirement Home</option>';
strHTML += '<option value="Other: Woodland Plantation">Other: Woodland Plantation</option>';
strHTML += '<option value="Other: Yorkville Clcp">Other: Yorkville Clcp</option>';
strHTML += '<option value="Park: Accotink Creek">Park: Accotink Creek</option>';
strHTML += '<option value="Park: Barcroft (Arlington)">Park: Barcroft (Arlington)</option>';
strHTML += '<option value="Park: Bluemont">Park: Bluemont</option>';
strHTML += '<option value="Park: Bull Run Regional">Park: Bull Run Regional</option>';
strHTML += '<option value="Park: Burke Lake">Park: Burke Lake</option>';
strHTML += '<option value="Park: Calvert Cliffs State">Park: Calvert Cliffs State</option>';
strHTML += '<option value="Park: Claude Moore">Park: Claude Moore</option>';
strHTML += '<option value="Park: Clemyjontri">Park: Clemyjontri</option>';
strHTML += '<option value="Park: Cub Run">Park: Cub Run</option>';
strHTML += '<option value="Park: Dulles Golf Center & Sports">Park: Dulles Golf Center & Sports</option>';
strHTML += '<option value="Park: Edsall Center">Park: Edsall Center</option>';
strHTML += '<option value="Park: Ellanor C. Lawrence">Park: Ellanor C. Lawrence</option>';
strHTML += '<option value="Park: Eugene Simpson">Park: Eugene Simpson</option>';
strHTML += '<option value="Park: Flight Trampoline">Park: Flight Trampoline</option>';
strHTML += '<option value="Park: Fort Hunt">Park: Fort Hunt</option>';
strHTML += '<option value="Park: Franconia">Park: Franconia</option>';
strHTML += '<option value="Park: Frying Pan">Park: Frying Pan</option>';
strHTML += '<option value="Park: Funland">Park: Funland</option>';
strHTML += '<option value="Park: Glen Echo :  Md">Park: Glen Echo :  Md</option>';
strHTML += '<option value="Park: Gravelly Point">Park: Gravelly Point</option>';
strHTML += '<option value="Park: Great Falls">Park: Great Falls</option>';
strHTML += '<option value="Park: Great Meadows (The Plains)">Park: Great Meadows (The Plains)</option>';
strHTML += '<option value="Park: Green Spring Garden">Park: Green Spring Garden</option>';
strHTML += '<option value="Park: Gunpowder Falls State">Park: Gunpowder Falls State</option>';
strHTML += '<option value="Park: Hemlock Overlook">Park: Hemlock Overlook</option>';
strHTML += '<option value="Park: Huntley Meadows">Park: Huntley Meadows</option>';
strHTML += '<option value="Park: Jefferson District Golf Course">Park: Jefferson District Golf Course</option>';
strHTML += '<option value="Park: Jefferson Mini Golf">Park: Jefferson Mini Golf</option>';
strHTML += '<option value="Park: Kenilworth">Park: Kenilworth</option>';
strHTML += '<option value="Park: Lake Accotink">Park: Lake Accotink</option>';
strHTML += '<option value="Park: Lake Fairfax">Park: Lake Fairfax</option>';
strHTML += '<option value="Park: Leesburg Animal">Park: Leesburg Animal</option>';
strHTML += '<option value="Park: Leesylvania State">Park: Leesylvania State</option>';
strHTML += '<option value="Park: Lewinsville">Park: Lewinsville</option>';
strHTML += '<option value="Park: Loriella State">Park: Loriella State</option>';
strHTML += '<option value="Park: Mason District">Park: Mason District</option>';
strHTML += '<option value="Park: Mason Neck">Park: Mason Neck</option>';
strHTML += '<option value="Park: Nationals">Park: Nationals</option>';
strHTML += '<option value="Park: Nottoway">Park: Nottoway</option>';
strHTML += '<option value="Park: Ossian Hall">Park: Ossian Hall</option>';
strHTML += '<option value="Park: Pohick Bay">Park: Pohick Bay</option>';
strHTML += '<option value="Park: Pohick Bay Regional & Golf Course">Park: Pohick Bay Regional & Golf Course</option>';
strHTML += '<option value="Park: Pole Green">Park: Pole Green</option>';
strHTML += '<option value="Park: Potomac Crossing">Park: Potomac Crossing</option>';
strHTML += '<option value="Park: Potomac Overlook Regional">Park: Potomac Overlook Regional</option>';
strHTML += '<option value="Park: Prince William Forest">Park: Prince William Forest</option>';
strHTML += '<option value="Park: Quincy">Park: Quincy</option>';
strHTML += '<option value="Park: Redskin">Park: Redskin</option>';
strHTML += '<option value="Park: Riverbend">Park: Riverbend</option>';
strHTML += '<option value="Park: Rocky Run">Park: Rocky Run</option>';
strHTML += '<option value="Park: Rope Adventure">Park: Rope Adventure</option>';
strHTML += '<option value="Park: Sandy Run Regional">Park: Sandy Run Regional</option>';
strHTML += '<option value="Park: Simpson">Park: Simpson</option>';
strHTML += '<option value="Park: Splash Down Water">Park: Splash Down Water</option>';
strHTML += '<option value="Park: Temple Hall Farm Regional">Park: Temple Hall Farm Regional</option>';
strHTML += '<option value="Park: University Of Maryland, College">Park: University Of Maryland, College</option>';
strHTML += '<option value="Park: Upton Hill Regional">Park: Upton Hill Regional</option>';
strHTML += '<option value="Park: Wakefield Skate">Park: Wakefield Skate</option>';
strHTML += '<option value="Park: Watkins Regional">Park: Watkins Regional</option>';
strHTML += '<option value="Park: Word Of Grace / Old Redskin">Park: Word Of Grace / Old Redskin</option>';
strHTML += '<option value="Park: Zoofari Animal">Park: Zoofari Animal</option>';
strHTML += '<option value="Reccenter: Claude Moore">Reccenter: Claude Moore</option>';
strHTML += '<option value="Reccenter: Lee District">Reccenter: Lee District</option>';
strHTML += '<option value="Recenter: Audrey Moore">Recenter: Audrey Moore</option>';
strHTML += '<option value="Recenter: Cub Run">Recenter: Cub Run</option>';
strHTML += '<option value="Recenter: George Washington">Recenter: George Washington</option>';
strHTML += '<option value="Recenter: Lee">Recenter: Lee</option>';
strHTML += '<option value="Recenter: Lee District">Recenter: Lee District</option>';
strHTML += '<option value="Recenter: Mount Vernon">Recenter: Mount Vernon</option>';
strHTML += '<option value="Recenter: Mt Vernon">Recenter: Mt Vernon</option>';
strHTML += '<option value="Recenter: Oak Marr">Recenter: Oak Marr</option>';
strHTML += '<option value="Recenter: Providence">Recenter: Providence</option>';
strHTML += '<option value="Recenter: South Run">Recenter: South Run</option>';
strHTML += '<option value="Recenter: Spring Hill">Recenter: Spring Hill</option>';
strHTML += '<option value="Recenter: Wakefield">Recenter: Wakefield</option>';
strHTML += '<option value="Theater: Adventure Theatre">Theater: Adventure Theatre</option>';
strHTML += '<option value="Theater: Amc">Theater: Amc</option>';
strHTML += '<option value="Theater: Arena Stage">Theater: Arena Stage</option>';
strHTML += '<option value="Theater: Bow Tie Cinema">Theater: Bow Tie Cinema</option>';
strHTML += '<option value="Theater: Cinemark">Theater: Cinemark</option>';
strHTML += '<option value="Theater: Cobb Village 12">Theater: Cobb Village 12</option>';
strHTML += '<option value="Theater: Constellation Theatre">Theater: Constellation Theatre</option>';
strHTML += '<option value="Theater: Hylton Performing Arts Center">Theater: Hylton Performing Arts Center</option>';
strHTML += '<option value="Theater: Imagination Stage">Theater: Imagination Stage</option>';
strHTML += '<option value="Theater: Regal">Theater: Regal</option>';
strHTML += '<option value="Theater: Synetic Theatre">Theater: Synetic Theatre</option>';
strHTML += '<option value="Theater: University Mall Theater">Theater: University Mall Theater</option>';
document.getElementById(`ftselector${optVal}`).innerHTML = strHTML;
