const url = window.location.pathname;
const filename = url.substring(url.lastIndexOf('/')+1);
const optVal = (filename === "index2.html") ? "S" : "";
strHTML = '<option value="">--Select Location--</option>';
strHTML += '<option value="Center: Bryant ALC">Center: Bryant ALC</option>';
strHTML += '<option value="Center: Burke School">Center: Burke School</option>';
strHTML += '<option value="Center: Cedar Lane Center">Center: Cedar Lane Center</option>';
strHTML += '<option value="Center: Davis Vocational Center">Center: Davis Vocational Center</option>';
strHTML += '<option value="Center: Lorton Center">Center: Lorton Center</option>';
strHTML += '<option value="Center: Montrose ALC">Center: Montrose ALC</option>';
strHTML += '<option value="Center: Pimmit Hills Center">Center: Pimmit Hills Center</option>';
strHTML += '<option value="Center: Plum Center">Center: Plum Center</option>';
strHTML += '<option value="Center: Pulley Center">Center: Pulley Center</option>';
strHTML += '<option value="Center: Quander Road Center">Center: Quander Road Center</option>';
strHTML += '<option value="Community: Baileys Community Center">Community: Baileys Community Center</option>';
strHTML += '<option value="Community: Falls Church Community Center">Community: Falls Church Community Center</option>';
strHTML += '<option value="Community: Graham Road Community Center">Community: Graham Road Community Center</option>';
strHTML += '<option value="Community: Gum Springs Community Ctr">Community: Gum Springs Community Ctr</option>';
strHTML += '<option value="Community: Herndon Community Center">Community: Herndon Community Center</option>';
strHTML += '<option value="Community: Huntington Community Center">Community: Huntington Community Center</option>';
strHTML += '<option value="Community: James Lee Community Center">Community: James Lee Community Center</option>';
strHTML += '<option value="Community: Mclean Community Ctr">Community: Mclean Community Ctr</option>';
strHTML += '<option value="Community: Mott Community Center">Community: Mott Community Center</option>';
strHTML += '<option value="Community: Pinn Community Center">Community: Pinn Community Center</option>';
strHTML += '<option value="Community: Providence Community Center">Community: Providence Community Center</option>';
strHTML += '<option value="Community: Reston Community Center">Community: Reston Community Center</option>';
strHTML += '<option value="Community: Southgate Community Center">Community: Southgate Community Center</option>';
strHTML += '<option value="Community: Tj Community Center">Community: Tj Community Center</option>';
strHTML += '<option value="Community: Vienna Community Center">Community: Vienna Community Center</option>';
strHTML += '<option value="DC: Air & Space Museum">DC: Air & Space Museum</option>';
strHTML += '<option value="DC: American Art Museum">DC: American Art Museum</option>';
strHTML += '<option value="DC: Arthur M Sackler Gallery">DC: Arthur M Sackler Gallery</option>';
strHTML += '<option value="DC: Bureau Of Engraving">DC: Bureau Of Engraving</option>';
strHTML += '<option value="DC: Capital One Arena">DC: Capital One Arena</option>';
strHTML += '<option value="DC: Dar Constitution Hall">DC: Dar Constitution Hall</option>';
strHTML += '<option value="DC: Discovery Theatre">DC: Discovery Theatre</option>';
strHTML += '<option value="DC: Fdr Monument">DC: Fdr Monument</option>';
strHTML += '<option value="DC: Federal Reserve Building">DC: Federal Reserve Building</option>';
strHTML += '<option value="DC: Folger Theatre">DC: Folger Theatre</option>';
strHTML += '<option value="DC: Fords Theatre">DC: Fords Theatre</option>';
strHTML += '<option value="DC: Gala Theater">DC: Gala Theater</option>';
strHTML += '<option value="DC: Gang Plank Marina">DC: Gang Plank Marina</option>';
strHTML += '<option value="DC: Georgetown University">DC: Georgetown University</option>';
strHTML += '<option value="DC: Gwu Lisner Auditorium">DC: Gwu Lisner Auditorium</option>';
strHTML += '<option value="DC: Hains Point">DC: Hains Point</option>';
strHTML += '<option value="DC: Harman CenterSidney Harman Hall">DC: Harman Center :  Sidney Harman Hall</option>';
strHTML += '<option value="DC: Hirschorn Museum">DC: Hirschorn Museum</option>';
strHTML += '<option value="DC: Howard University">DC: Howard University</option>';
strHTML += '<option value="DC: Jefferson Memorial">DC: Jefferson Memorial</option>';
strHTML += '<option value="DC: Kennedy Center">DC: Kennedy Center</option>';
strHTML += '<option value="DC: Lansburgh Theatre">DC: Lansburgh Theatre</option>';
strHTML += '<option value="DC: Library Of Congress">DC: Library Of Congress</option>';
strHTML += '<option value="DC: Lincoln Memorial">DC: Lincoln Memorial</option>';
strHTML += '<option value="DC: Lisner Auditorium">DC: Lisner Auditorium</option>';
strHTML += '<option value="DC: National Arboretum">DC: National Arboretum</option>';
strHTML += '<option value="DC: National Archives">DC: National Archives</option>';
strHTML += '<option value="DC: National Building Museum">DC: National Building Museum</option>';
strHTML += '<option value="DC: National Cathedral School">DC: National Cathedral School</option>';
strHTML += '<option value="DC: National Gallery Of Art">DC: National Gallery Of Art</option>';
strHTML += '<option value="DC: National Geographic Museum">DC: National Geographic Museum</option>';
strHTML += '<option value="DC: National Law Enforcement Museum">DC: National Law Enforcement Museum</option>';
strHTML += '<option value="DC: National Museum Of African American History">DC: National Museum Of African American History</option>';
strHTML += '<option value="DC: National Museum Of African Art">DC: National Museum Of African Art</option>';
strHTML += '<option value="DC: National Museum Of American History">DC: National Museum Of American History</option>';
strHTML += '<option value="DC: National Museum Of Natural History">DC: National Museum Of Natural History</option>';
strHTML += '<option value="DC: National Museum Of The American Indian">DC: National Museum Of The American Indian</option>';
strHTML += '<option value="DC: National Postal Museum">DC: National Postal Museum</option>';
strHTML += '<option value="DC: National Zoo">DC: National Zoo</option>';
strHTML += '<option value="DC: NBC 4 Studio">DC: NBC 4 Studio</option>';
strHTML += '<option value="DC: Newseum">DC: Newseum</option>';
strHTML += '<option value="DC: Portrait Gallery">DC: Portrait Gallery</option>';
strHTML += '<option value="DC: Puppet Playhouse">DC: Puppet Playhouse</option>';
strHTML += '<option value="DC: Shakespeare Theatre">DC: Shakespeare Theatre</option>';
strHTML += '<option value="DC: Sydney Harmon Hall">DC: Sydney Harmon Hall</option>';
strHTML += '<option value="DC: The Phillips Collection">DC: The Phillips Collection</option>';
strHTML += '<option value="DC: Theater Alliance">DC: Theater Alliance</option>';
strHTML += '<option value="DC: United States Botanic Gardens">DC: United States Botanic Gardens</option>';
strHTML += '<option value="DC: United States Holocaust Memorial Museum">DC: United States Holocaust Memorial Museum</option>';
strHTML += '<option value="DC: Us Capitol">DC: Us Capitol</option>';
strHTML += '<option value="DC: Us Supreme Court">DC: Us Supreme Court</option>';
strHTML += '<option value="DC: Washington Convention Center">DC: Washington Convention Center</option>';
strHTML += '<option value="DC: Washington Monument">DC: Washington Monument</option>';
strHTML += '<option value="DC: Washington Post">DC: Washington Post</option>';
strHTML += '<option value="DC: Washington Youth Garden">DC: Washington Youth Garden</option>';
strHTML += '<option value="DC: White House">DC: White House</option>';
strHTML += '<option value="DC: World War II Memorial">DC: World War II Memorial</option>';
strHTML += '<option value="ES: Aldrin">ES: Aldrin</option>';
strHTML += '<option value="ES: Annandale Terrace">ES: Annandale Terrace</option>';
strHTML += '<option value="ES: Armstrong">ES: Armstrong</option>';
strHTML += '<option value="ES: Baileys">ES: Baileys</option>';
strHTML += '<option value="ES: Baileys Upper">ES: Baileys Upper</option>';
strHTML += '<option value="ES: Beech Tree">ES: Beech Tree</option>';
strHTML += '<option value="ES: Belle View">ES: Belle View</option>';
strHTML += '<option value="ES: Belvedere">ES: Belvedere</option>';
strHTML += '<option value="ES: Bonnie Brae">ES: Bonnie Brae</option>';
strHTML += '<option value="ES: Braddock">ES: Braddock</option>';
strHTML += '<option value="ES: Bren Mar Park">ES: Bren Mar Park</option>';
strHTML += '<option value="ES: Brookfield">ES: Brookfield</option>';
strHTML += '<option value="ES: Bucknell">ES: Bucknell</option>';
strHTML += '<option value="ES: Bull Run">ES: Bull Run</option>';
strHTML += '<option value="ES: Bush Hill">ES: Bush Hill</option>';
strHTML += '<option value="ES: Camelot">ES: Camelot</option>';
strHTML += '<option value="ES: Cameron">ES: Cameron</option>';
strHTML += '<option value="ES: Canterbury Woods">ES: Canterbury Woods</option>';
strHTML += '<option value="ES: Cardinal Forest">ES: Cardinal Forest</option>';
strHTML += '<option value="ES: Centre Ridge">ES: Centre Ridge</option>';
strHTML += '<option value="ES: Centreville">ES: Centreville</option>';
strHTML += '<option value="ES: Cherry Run">ES: Cherry Run</option>';
strHTML += '<option value="ES: Chesterbrook">ES: Chesterbrook</option>';
strHTML += '<option value="ES: Churchill Road">ES: Churchill Road</option>';
strHTML += '<option value="ES: Clearview">ES: Clearview</option>';
strHTML += '<option value="ES: Clermont">ES: Clermont</option>';
strHTML += '<option value="ES: Coates">ES: Coates</option>';
strHTML += '<option value="ES: Colin L. Powell">ES: Colin L. Powell</option>';
strHTML += '<option value="ES: Colin Powell">ES: Colin Powell</option>';
strHTML += '<option value="ES: Columbia">ES: Columbia</option>';
strHTML += '<option value="ES: Colvin Run">ES: Colvin Run</option>';
strHTML += '<option value="ES: Crestwood">ES: Crestwood</option>';
strHTML += '<option value="ES: Crossfield">ES: Crossfield</option>';
strHTML += '<option value="ES: Cub Run">ES: Cub Run</option>';
strHTML += '<option value="ES: Cunningham Park">ES: Cunningham Park</option>';
strHTML += '<option value="ES: Daniels Run">ES: Daniels Run</option>';
strHTML += '<option value="ES: Deer Park">ES: Deer Park</option>';
strHTML += '<option value="ES: Dogwood">ES: Dogwood</option>';
strHTML += '<option value="ES: Dranesville">ES: Dranesville</option>';
strHTML += '<option value="ES: Eagle View">ES: Eagle View</option>';
strHTML += '<option value="ES: Fairfax Villa">ES: Fairfax Villa</option>';
strHTML += '<option value="ES: Fairhill">ES: Fairhill</option>';
strHTML += '<option value="ES: Fairview">ES: Fairview</option>';
strHTML += '<option value="ES: Flint Hill">ES: Flint Hill</option>';
strHTML += '<option value="ES: Floris">ES: Floris</option>';
strHTML += '<option value="ES: Forest Edge">ES: Forest Edge</option>';
strHTML += '<option value="ES: Forestdale">ES: Forestdale</option>';
strHTML += '<option value="ES: Forestville">ES: Forestville</option>';
strHTML += '<option value="ES: Fort Belvoir">ES: Fort Belvoir</option>';
strHTML += '<option value="ES: Fort Belvoir Upper">ES: Fort Belvoir Upper</option>';
strHTML += '<option value="ES: Fort Hunt">ES: Fort Hunt</option>';
strHTML += '<option value="ES: Fox Mill">ES: Fox Mill</option>';
strHTML += '<option value="ES: Franconia">ES: Franconia</option>';
strHTML += '<option value="ES: Franklin Sherman">ES: Franklin Sherman</option>';
strHTML += '<option value="ES: Freedom Hill">ES: Freedom Hill</option>';
strHTML += '<option value="ES: Garfield">ES: Garfield</option>';
strHTML += '<option value="ES: Glen Forest">ES: Glen Forest</option>';
strHTML += '<option value="ES: Graham Road">ES: Graham Road</option>';
strHTML += '<option value="ES: Great Falls">ES: Great Falls</option>';
strHTML += '<option value="ES: Greenbriar East">ES: Greenbriar East</option>';
strHTML += '<option value="ES: Greenbriar West">ES: Greenbriar West</option>';
strHTML += '<option value="ES: Groveton">ES: Groveton</option>';
strHTML += '<option value="ES: Gunston">ES: Gunston</option>';
strHTML += '<option value="ES: Halley">ES: Halley</option>';
strHTML += '<option value="ES: Haycock">ES: Haycock</option>';
strHTML += '<option value="ES: Hayfield">ES: Hayfield</option>';
strHTML += '<option value="ES: Herndon">ES: Herndon</option>';
strHTML += '<option value="ES: Hollin Meadows">ES: Hollin Meadows</option>';
strHTML += '<option value="ES: Hunt Valley">ES: Hunt Valley</option>';
strHTML += '<option value="ES: Hunters Woods">ES: Hunters Woods</option>';
strHTML += '<option value="ES: Hutchison">ES: Hutchison</option>';
strHTML += '<option value="ES: Hybla Valley">ES: Hybla Valley</option>';
strHTML += '<option value="ES: Island Creek">ES: Island Creek</option>';
strHTML += '<option value="ES: Keene Mill">ES: Keene Mill</option>';
strHTML += '<option value="ES: Kent Gardens">ES: Kent Gardens</option>';
strHTML += '<option value="ES: Kings Glen">ES: Kings Glen</option>';
strHTML += '<option value="ES: Kings Park">ES: Kings Park</option>';
strHTML += '<option value="ES: Lake Anne">ES: Lake Anne</option>';
strHTML += '<option value="ES: Lane">ES: Lane</option>';
strHTML += '<option value="ES: Laurel Hill">ES: Laurel Hill</option>';
strHTML += '<option value="ES: Laurel Ridge">ES: Laurel Ridge</option>';
strHTML += '<option value="ES: Lees Corner">ES: Lees Corner</option>';
strHTML += '<option value="ES: Lemon Road">ES: Lemon Road</option>';
strHTML += '<option value="ES: Little Run">ES: Little Run</option>';
strHTML += '<option value="ES: London Towne">ES: London Towne</option>';
strHTML += '<option value="ES: Lorton Station">ES: Lorton Station</option>';
strHTML += '<option value="ES: Louise Archer">ES: Louise Archer</option>';
strHTML += '<option value="ES: Lynbrook">ES: Lynbrook</option>';
strHTML += '<option value="ES: Mantua">ES: Mantua</option>';
strHTML += '<option value="ES: Marshall Road">ES: Marshall Road</option>';
strHTML += '<option value="ES: Mason Crest">ES: Mason Crest</option>';
strHTML += '<option value="ES: Mcnair">ES: Mcnair</option>';
strHTML += '<option value="ES: Mosby Woods">ES: Mosby Woods</option>';
strHTML += '<option value="ES: Mount Eagle">ES: Mount Eagle</option>';
strHTML += '<option value="ES: Mount Vernon Woods">ES: Mount Vernon Woods</option>';
strHTML += '<option value="ES: Mount Vernontate">ES: Mount Vernontate</option>';
strHTML += '<option value="ES: Navy">ES: Navy</option>';
strHTML += '<option value="ES: Newington Forest">ES: Newington Forest</option>';
strHTML += '<option value="ES: North Springfield">ES: North Springfield</option>';
strHTML += '<option value="ES: Oak Hill">ES: Oak Hill</option>';
strHTML += '<option value="ES: Oak View">ES: Oak View</option>';
strHTML += '<option value="ES: Oakton">ES: Oakton</option>';
strHTML += '<option value="ES: Olde Creek">ES: Olde Creek</option>';
strHTML += '<option value="ES: Orange Hunt">ES: Orange Hunt</option>';
strHTML += '<option value="ES: Parklawn">ES: Parklawn</option>';
strHTML += '<option value="ES: Pine Spring">ES: Pine Spring</option>';
strHTML += '<option value="ES: Poplar Tree">ES: Poplar Tree</option>';
strHTML += '<option value="ES: Providence">ES: Providence</option>';
strHTML += '<option value="ES: Ravensworth">ES: Ravensworth</option>';
strHTML += '<option value="ES: Riverside">ES: Riverside</option>';
strHTML += '<option value="ES: Rolling Valley">ES: Rolling Valley</option>';
strHTML += '<option value="ES: Rose Hill">ES: Rose Hill</option>';
strHTML += '<option value="ES: Sangster">ES: Sangster</option>';
strHTML += '<option value="ES: Saratoga">ES: Saratoga</option>';
strHTML += '<option value="ES: Shrevewood">ES: Shrevewood</option>';
strHTML += '<option value="ES: Silverbrook">ES: Silverbrook</option>';
strHTML += '<option value="ES: Sleepy Hollow">ES: Sleepy Hollow</option>';
strHTML += '<option value="ES: Spring Hill">ES: Spring Hill</option>';
strHTML += '<option value="ES: Springfieldtates">ES: Springfieldtates</option>';
strHTML += '<option value="ES: Stenwood">ES: Stenwood</option>';
strHTML += '<option value="ES: Stratford Landing">ES: Stratford Landing</option>';
strHTML += '<option value="ES: Sunrise Valley">ES: Sunrise Valley</option>';
strHTML += '<option value="ES: Terra Centre">ES: Terra Centre</option>';
strHTML += '<option value="ES: Terraset">ES: Terraset</option>';
strHTML += '<option value="ES: Timber Lane">ES: Timber Lane</option>';
strHTML += '<option value="ES: Union Mill">ES: Union Mill</option>';
strHTML += '<option value="ES: Vienna">ES: Vienna</option>';
strHTML += '<option value="ES: Virginia Run">ES: Virginia Run</option>';
strHTML += '<option value="ES: Wakefield Forest">ES: Wakefield Forest</option>';
strHTML += '<option value="ES: Waples Mill">ES: Waples Mill</option>';
strHTML += '<option value="ES: Washington Mill">ES: Washington Mill</option>';
strHTML += '<option value="ES: Waynewood">ES: Waynewood</option>';
strHTML += '<option value="ES: West Springfield">ES: West Springfield</option>';
strHTML += '<option value="ES: Westbriar">ES: Westbriar</option>';
strHTML += '<option value="ES: Westgate">ES: Westgate</option>';
strHTML += '<option value="ES: Westlawn">ES: Westlawn</option>';
strHTML += '<option value="ES: Weyanoke">ES: Weyanoke</option>';
strHTML += '<option value="ES: White Oaks">ES: White Oaks</option>';
strHTML += '<option value="ES: Willow Springs">ES: Willow Springs</option>';
strHTML += '<option value="ES: Wolftrap">ES: Wolftrap</option>';
strHTML += '<option value="ES: Woodburn">ES: Woodburn</option>';
strHTML += '<option value="ES: Woodlawn">ES: Woodlawn</option>';
strHTML += '<option value="ES: Woodley Hills">ES: Woodley Hills</option>';
strHTML += '<option value="Farm: Accokeek Colonial">Farm: Accokeek Colonial</option>';
strHTML += '<option value="Farm: Amazing Farm Fun">Farm: Amazing Farm Fun</option>';
strHTML += '<option value="Farm: Arcadia">Farm: Arcadia</option>';
strHTML += '<option value="Farm: Ballentine">Farm: Ballentine</option>';
strHTML += '<option value="Farm: Cows N Corn">Farm: Cows N Corn</option>';
strHTML += '<option value="Farm: Cox">Farm: Cox</option>';
strHTML += '<option value="Farm: Great Country Farms">Farm: Great Country Farms</option>';
strHTML += '<option value="Farm: Hartland Farm And Orchard">Farm: Hartland Farm And Orchard</option>';
strHTML += '<option value="Farm: Kidwell Farms">Farm: Kidwell Farms</option>';
strHTML += '<option value="Farm: Miller Farms">Farm: Miller Farms</option>';
strHTML += '<option value="Farm: Oxon Hill">Farm: Oxon Hill</option>';
strHTML += '<option value="Farm: Panorama">Farm: Panorama</option>';
strHTML += '<option value="Farm: Potomac Vegetable">Farm: Potomac Vegetable</option>';
strHTML += '<option value="Farm: Shlagel Farms">Farm: Shlagel Farms</option>';
strHTML += '<option value="Farm: Ticonderoga">Farm: Ticonderoga</option>';
strHTML += '<option value="Farm: Wayside">Farm: Wayside</option>';
strHTML += '<option value="Farm: Whitehall">Farm: Whitehall</option>';
strHTML += '<option value="GMU:  Center For The Arts">GMU:  Center For The Arts</option>';
strHTML += '<option value="GMU:  Eagle Bank Arena">GMU:  Eagle Bank Arena</option>';
strHTML += '<option value="GMU :  Patriot Center">GMU :  Patriot Center</option>';
strHTML += '<option value="GMU:  The Edge">GMU:  The Edge</option>';
strHTML += '<option value="HS: Annandale">HS: Annandale</option>';
strHTML += '<option value="HS: Arundel">HS: Arundel</option>';
strHTML += '<option value="HS: Atlee">HS: Atlee</option>';
strHTML += '<option value="HS: Battlefield">HS: Battlefield</option>';
strHTML += '<option value="HS: Bishop Ireton">HS: Bishop Ireton</option>';
strHTML += '<option value="HS: Bishop Mcnamara">HS: Bishop Mcnamara</option>';
strHTML += '<option value="HS: Boonsboro">HS: Boonsboro</option>';
strHTML += '<option value="HS: Brentsville District">HS: Brentsville District</option>';
strHTML += '<option value="HS: Briar Woods">HS: Briar Woods</option>';
strHTML += '<option value="HS: Broad Run">HS: Broad Run</option>';
strHTML += '<option value="HS: Brooke Point">HS: Brooke Point</option>';
strHTML += '<option value="HS: Bryant Alt">HS: Bryant Alt</option>';
strHTML += '<option value="HS: Centreville">HS: Centreville</option>';
strHTML += '<option value="HS: Chantilly">HS: Chantilly</option>';
strHTML += '<option value="HS: Charles J. Colgan Sr.">HS: Charles J. Colgan Sr.</option>';
strHTML += '<option value="HS: Colonial Forge">HS: Colonial Forge</option>';
strHTML += '<option value="HS: Culpeper County">HS: Culpeper County</option>';
strHTML += '<option value="HS: Damascus">HS: Damascus</option>';
strHTML += '<option value="HS: Dominion">HS: Dominion</option>';
strHTML += '<option value="HS: Dunbar">HS: Dunbar</option>';
strHTML += '<option value="HS: Dundalk">HS: Dundalk</option>';
strHTML += '<option value="HS: Eastern View">HS: Eastern View</option>';
strHTML += '<option value="HS: Easton">HS: Easton</option>';
strHTML += '<option value="HS: Edison">HS: Edison</option>';
strHTML += '<option value="HS: Episcopal">HS: Episcopal</option>';
strHTML += '<option value="HS: Fairfax">HS: Fairfax</option>';
strHTML += '<option value="HS: Falls Church">HS: Falls Church</option>';
strHTML += '<option value="HS: Fauquier">HS: Fauquier</option>';
strHTML += '<option value="HS: Flint Hill">HS: Flint Hill</option>';
strHTML += '<option value="HS: Forest Park">HS: Forest Park</option>';
strHTML += '<option value="HS: Freedom (Loudoun)">HS: Freedom (Loudoun)</option>';
strHTML += '<option value="HS: Freedom (Prince William)">HS: Freedom (Prince William)</option>';
strHTML += '<option value="HS: Gar: Field">HS: Gar: Field</option>';
strHTML += '<option value="HS: George Mason">HS: George Mason</option>';
strHTML += '<option value="HS: Glen Allen">HS: Glen Allen</option>';
strHTML += '<option value="HS: Gonzaga College">HS: Gonzaga College</option>';
strHTML += '<option value="HS: Handley">HS: Handley</option>';
strHTML += '<option value="HS: Harrisonburg">HS: Harrisonburg</option>';
strHTML += '<option value="HS: Hayfield Sec">HS: Hayfield Sec</option>';
strHTML += '<option value="HS: Hd Woodson">HS: Hd Woodson</option>';
strHTML += '<option value="HS: Heritage">HS: Heritage</option>';
strHTML += '<option value="HS: Herndon">HS: Herndon</option>';
strHTML += '<option value="HS: Hylton">HS: Hylton</option>';
strHTML += '<option value="HS: John Champe">HS: John Champe</option>';
strHTML += '<option value="HS: Justice">HS: Justice</option>';
strHTML += '<option value="HS: King George">HS: King George</option>';
strHTML += '<option value="HS: Lake Braddock Sec">HS: Lake Braddock Sec</option>';
strHTML += '<option value="HS: Langley">HS: Langley</option>';
strHTML += '<option value="HS: Lee">HS: Lee</option>';
strHTML += '<option value="HS: Lee: Davis">HS: Lee: Davis</option>';
strHTML += '<option value="HS: Leonardtown">HS: Leonardtown</option>';
strHTML += '<option value="HS: Liberty">HS: Liberty</option>';
strHTML += '<option value="HS: Loudon Valley">HS: Loudon Valley</option>';
strHTML += '<option value="HS: Loudoun County">HS: Loudoun County</option>';
strHTML += '<option value="HS: Loudoun Valley">HS: Loudoun Valley</option>';
strHTML += '<option value="HS: Madeira">HS: Madeira</option>';
strHTML += '<option value="HS: Madison">HS: Madison</option>';
strHTML += '<option value="HS: Magruder">HS: Magruder</option>';
strHTML += '<option value="HS: Marshall">HS: Marshall</option>';
strHTML += '<option value="HS: Mcdonough">HS: Mcdonough</option>';
strHTML += '<option value="HS: Mclean">HS: Mclean</option>';
strHTML += '<option value="HS: Millbrook">HS: Millbrook</option>';
strHTML += '<option value="HS: Minnie Howard School">HS: Minnie Howard School</option>';
strHTML += '<option value="HS: Montgomery Blair">HS: Montgomery Blair</option>';
strHTML += '<option value="HS: Mount Vernon">HS: Mount Vernon</option>';
strHTML += '<option value="HS: Mountain View">HS: Mountain View</option>';
strHTML += '<option value="HS: Mountain View Alt">HS: Mountain View Alt</option>';
strHTML += '<option value="HS: North Stafford">HS: North Stafford</option>';
strHTML += '<option value="HS: Northwest">HS: Northwest</option>';
strHTML += '<option value="HS: Oakton">HS: Oakton</option>';
strHTML += '<option value="HS: Oconnell">HS: Oconnell</option>';
strHTML += '<option value="HS: Osbourn">HS: Osbourn</option>';
strHTML += '<option value="HS: Osbourn Park">HS: Osbourn Park</option>';
strHTML += '<option value="HS: Our Lady Of Good Counsel">HS: Our Lady Of Good Counsel</option>';
strHTML += '<option value="HS: Park View">HS: Park View</option>';
strHTML += '<option value="HS: Patriot">HS: Patriot</option>';
strHTML += '<option value="HS: Patuxent">HS: Patuxent</option>';
strHTML += '<option value="HS: Paul Vi">HS: Paul Vi</option>';
strHTML += '<option value="HS: Poolesville, Maryland">HS: Poolesville, Maryland</option>';
strHTML += '<option value="HS: Potomac :  Dumfries">HS: Potomac :  Dumfries</option>';
strHTML += '<option value="HS: Potomac Falls :  Sterling">HS: Potomac Falls :  Sterling</option>';
strHTML += '<option value="HS: Riverbend">HS: Riverbend</option>';
strHTML += '<option value="HS: Riverside">HS: Riverside</option>';
strHTML += '<option value="HS: Robinson Sec">HS: Robinson Sec</option>';
strHTML += '<option value="HS: Rock Ridge">HS: Rock Ridge</option>';
strHTML += '<option value="HS: Roosevelt">HS: Roosevelt</option>';
strHTML += '<option value="HS: Sidwell Friends">HS: Sidwell Friends</option>';
strHTML += '<option value="HS: South County">HS: South County</option>';
strHTML += '<option value="HS: South Lakes">HS: South Lakes</option>';
strHTML += '<option value="HS: Spotsylvania">HS: Spotsylvania</option>';
strHTML += '<option value="HS: St John Paul The Great">HS: St John Paul The Great</option>';
strHTML += '<option value="HS: St. Johns College">HS: St. Johns College</option>';
strHTML += '<option value="HS: Stafford">HS: Stafford</option>';
strHTML += '<option value="HS: Stonebridge">HS: Stonebridge</option>';
strHTML += '<option value="HS: Stonewall Jackson">HS: Stonewall Jackson</option>';
strHTML += '<option value="HS: Tc Williams">HS: Tc Williams</option>';
strHTML += '<option value="HS: Tjhsst">HS: Tjhsst</option>';
strHTML += '<option value="HS: Tuscarora">HS: Tuscarora</option>';
strHTML += '<option value="HS: Urbana">HS: Urbana</option>';
strHTML += '<option value="HS: Wakefield">HS: Wakefield</option>';
strHTML += '<option value="HS: Washington: Lee">HS: Washington: Lee</option>';
strHTML += '<option value="HS: West Potomac">HS: West Potomac</option>';
strHTML += '<option value="HS: West Springfield">HS: West Springfield</option>';
strHTML += '<option value="HS: Westfield">HS: Westfield</option>';
strHTML += '<option value="HS: Woodbridge">HS: Woodbridge</option>';
strHTML += '<option value="HS: Woodgrove">HS: Woodgrove</option>';
strHTML += '<option value="HS: Woodson">HS: Woodson</option>';
strHTML += '<option value="HS: Yorktown">HS: Yorktown</option>';
strHTML += '<option value="MS: Alice Deal">MS: Alice Deal</option>';
strHTML += '<option value="MS: Carl Sandburg">MS: Carl Sandburg</option>';
strHTML += '<option value="MS: Carson">MS: Carson</option>';
strHTML += '<option value="MS: Cooper">MS: Cooper</option>';
strHTML += '<option value="MS: Francis Hammond">MS: Francis Hammond</option>';
strHTML += '<option value="MS: Franklin">MS: Franklin</option>';
strHTML += '<option value="MS: Frost">MS: Frost</option>';
strHTML += '<option value="MS: Glasgow">MS: Glasgow</option>';
strHTML += '<option value="MS: Herndon">MS: Herndon</option>';
strHTML += '<option value="MS: Holmes">MS: Holmes</option>';
strHTML += '<option value="MS: Hughes">MS: Hughes</option>';
strHTML += '<option value="MS: Irving">MS: Irving</option>';
strHTML += '<option value="MS: Kenmore">MS: Kenmore</option>';
strHTML += '<option value="MS: Kenmore School">MS: Kenmore School</option>';
strHTML += '<option value="MS: Key">MS: Key</option>';
strHTML += '<option value="MS: Kilmer">MS: Kilmer</option>';
strHTML += '<option value="MS: Lanier">MS: Lanier</option>';
strHTML += '<option value="MS: Liberty">MS: Liberty</option>';
strHTML += '<option value="MS: Longfellow">MS: Longfellow</option>';
strHTML += '<option value="MS: Luther Jackson">MS: Luther Jackson</option>';
strHTML += '<option value="MS: Mary Ellen Henderson">MS: Mary Ellen Henderson</option>';
strHTML += '<option value="MS: Poe">MS: Poe</option>';
strHTML += '<option value="MS: Rocky Run">MS: Rocky Run</option>';
strHTML += '<option value="MS: Sandburg">MS: Sandburg</option>';
strHTML += '<option value="MS: South County">MS: South County</option>';
strHTML += '<option value="MS: Stone">MS: Stone</option>';
strHTML += '<option value="MS: Thomas Jefferson">MS: Thomas Jefferson</option>';
strHTML += '<option value="MS: Thoreau">MS: Thoreau</option>';
strHTML += '<option value="MS: Twain">MS: Twain</option>';
strHTML += '<option value="MS: Whitman">MS: Whitman</option>';
strHTML += '<option value="Museum: Air & Space :  Udvar Center">Museum: Air & Space :  Udvar Center</option>';
strHTML += '<option value="Museum: Alexandria Archeology">Museum: Alexandria Archeology</option>';
strHTML += '<option value="Museum: B & O Train">Museum: B & O Train</option>';
strHTML += '<option value="Museum: Carlyle House Apothecary">Museum: Carlyle House Apothecary</option>';
strHTML += '<option value="Museum: Glenstone">Museum: Glenstone</option>';
strHTML += '<option value="Museum: Heritage Farm">Museum: Heritage Farm</option>';
strHTML += '<option value="Museum: National Cryptologic">Museum: National Cryptologic</option>';
strHTML += '<option value="Museum: National Electronics">Museum: National Electronics</option>';
strHTML += '<option value="Museum: National Museum Of The Marine Corps">Museum: National Museum Of The Marine Corps</option>';
strHTML += '<option value="Nova :  Alexandria">Nova :  Alexandria</option>';
strHTML += '<option value="Nova :  Annandale">Nova :  Annandale</option>';
strHTML += '<option value="Nova :  Loudoun">Nova :  Loudoun</option>';
strHTML += '<option value="Nova :  Manassas">Nova :  Manassas</option>';
strHTML += '<option value="Nova :  Springfield Medical Campus">Nova :  Springfield Medical Campus</option>';
strHTML += '<option value="Other: Adventure Links">Other: Adventure Links</option>';
strHTML += '<option value="Other: Alan Leis Instr. Center">Other: Alan Leis Instr. Center</option>';
strHTML += '<option value="Other: American University">Other: American University</option>';
strHTML += '<option value="Other: Amf Bowling">Other: Amf Bowling</option>';
strHTML += '<option value="Other: Arlington National Cemetary">Other: Arlington National Cemetary</option>';
strHTML += '<option value="Other: Artechouse">Other: Artechouse</option>';
strHTML += '<option value="Other: Ashby Pond Conservatory Site">Other: Ashby Pond Conservatory Site</option>';
strHTML += '<option value="Other: Beehive Indoor Playground">Other: Beehive Indoor Playground</option>';
strHTML += '<option value="Other: Bellmont Bay Harbor">Other: Bellmont Bay Harbor</option>';
strHTML += '<option value="Other: Billy Beez">Other: Billy Beez</option>';
strHTML += '<option value="Other: Bowl America">Other: Bowl America</option>';
strHTML += '<option value="Other: Brightline Interactive">Other: Brightline Interactive</option>';
strHTML += '<option value="Other: Burke Garden Center">Other: Burke Garden Center</option>';
strHTML += '<option value="Other: Camp Crowell">Other: Camp Crowell</option>';
strHTML += '<option value="Other: Cedar Ridge Clcp">Other: Cedar Ridge Clcp</option>';
strHTML += '<option value="Other: Centreville Baptist Church">Other: Centreville Baptist Church</option>';
strHTML += '<option value="Other: Centrewood Plaza">Other: Centrewood Plaza</option>';
strHTML += '<option value="Other: Cherry Hill Farmhouse">Other: Cherry Hill Farmhouse</option>';
strHTML += '<option value="Other: Chesapeake Bay Foundation">Other: Chesapeake Bay Foundation</option>';
strHTML += '<option value="Other: Children Science Center">Other: Children Science Center</option>';
strHTML += '<option value="Other: Cia">Other: Cia</option>';
strHTML += '<option value="Other: Circuit Court Of Fairfax County">Other: Circuit Court Of Fairfax County</option>';
strHTML += '<option value="Other: Clay Cafe">Other: Clay Cafe</option>';
strHTML += '<option value="Other: Clearwater Nature Center">Other: Clearwater Nature Center</option>';
strHTML += '<option value="Other: Cole Sewage Treatment Plant">Other: Cole Sewage Treatment Plant</option>';
strHTML += '<option value="Other: Colonnade Shopping Center">Other: Colonnade Shopping Center</option>';
strHTML += '<option value="Other: Colvin Run Mill">Other: Colvin Run Mill</option>';
strHTML += '<option value="Other: Criminal Justice Academy">Other: Criminal Justice Academy</option>';
strHTML += '<option value="Other: Custom Ink">Other: Custom Ink</option>';
strHTML += '<option value="Other: Dave & Buster">Other: Dave & Buster</option>';
strHTML += '<option value="Other: Del Ray Cafe">Other: Del Ray Cafe</option>';
strHTML += '<option value="Other: Dogfish Head Alehouse">Other: Dogfish Head Alehouse</option>';
strHTML += '<option value="Other: Dominion Power">Other: Dominion Power</option>';
strHTML += '<option value="Other: Dulles Airport">Other: Dulles Airport</option>';
strHTML += '<option value="Other: Dulles Town Center">Other: Dulles Town Center</option>';
strHTML += '<option value="Other: Dyke Marsh Wildlife Preserve">Other: Dyke Marsh Wildlife Preserve</option>';
strHTML += '<option value="Other: Elks Club Of Fairfax">Other: Elks Club Of Fairfax</option>';
strHTML += '<option value="Other: Emmanuel Baptist Church">Other: Emmanuel Baptist Church</option>';
strHTML += '<option value="Other: Entertainment & Sports Arena">Other: Entertainment & Sports Arena</option>';
strHTML += '<option value="Other: Escape Room">Other: Escape Room</option>';
strHTML += '<option value="Other: Evergreen Sports Complex">Other: Evergreen Sports Complex</option>';
strHTML += '<option value="Other: Fair Oaks Mall">Other: Fair Oaks Mall</option>';
strHTML += '<option value="Other: Fairfax County Circuit Court">Other: Fairfax County Circuit Court</option>';
strHTML += '<option value="Other: Fairfax County Solid Waste Management I-95">Other: Fairfax County Solid Waste Management I-95</option>';
strHTML += '<option value="Other: Fairfax Recycling :  Disposal Facility">Other: Fairfax Recycling :  Disposal Facility</option>';
strHTML += '<option value="Other: Fairfax Ridge">Other: Fairfax Ridge</option>';
strHTML += '<option value="Other: Fedex Field">Other: Fedex Field</option>';
strHTML += '<option value="Other: Finance Park">Other: Finance Park</option>';
strHTML += '<option value="Other: Fort Belvoir Bowling Centr">Other: Fort Belvoir Bowling Centr</option>';
strHTML += '<option value="Other: Franconia Moose Lodge">Other: Franconia Moose Lodge</option>';
strHTML += '<option value="Other: Gallaudet University">Other: Gallaudet University</option>';
strHTML += '<option value="Other: Gatehouse Administrative Center">Other: Gatehouse Administrative Center</option>';
strHTML += '<option value="Other: Gaylord National Resort">Other: Gaylord National Resort</option>';
strHTML += '<option value="Other: Giant Food">Other: Giant Food</option>';
strHTML += '<option value="Other: Green Acres">Other: Green Acres</option>';
strHTML += '<option value="Other: Griffith Water Quality Plant">Other: Griffith Water Quality Plant</option>';
strHTML += '<option value="Other: Gunston Hall">Other: Gunston Hall</option>';
strHTML += '<option value="Other: Gunston Plaza">Other: Gunston Plaza</option>';
strHTML += '<option value="Other: Herndon Clcp">Other: Herndon Clcp</option>';
strHTML += '<option value="Other: Herndon Senior Center">Other: Herndon Senior Center</option>';
strHTML += '<option value="Other: Hidden Oaks Nature Center">Other: Hidden Oaks Nature Center</option>';
strHTML += '<option value="Other: Hidden Pond">Other: Hidden Pond</option>';
strHTML += '<option value="Other: Holiday Inn Express">Other: Holiday Inn Express</option>';
strHTML += '<option value="Other: Home Depot">Other: Home Depot</option>';
strHTML += '<option value="Other: Homeward Trails">Other: Homeward Trails</option>';
strHTML += '<option value="Other: Hood College">Other: Hood College</option>';
strHTML += '<option value="Other: Hyatt Regency Baltimore">Other: Hyatt Regency Baltimore</option>';
strHTML += '<option value="Other: IHOP">Other: IHOP</option>';
strHTML += '<option value="Other: Innerquest">Other: Innerquest</option>';
strHTML += '<option value="Other: Inova Fairfax Hospital">Other: Inova Fairfax Hospital</option>';
strHTML += '<option value="Other: Jerome Ford Nature Center">Other: Jerome Ford Nature Center</option>';
strHTML += '<option value="Other: Johns Hopkins University">Other: Johns Hopkins University</option>';
strHTML += '<option value="Other: Joint Base Andrews, Clinton Md">Other: Joint Base Andrews, Clinton Md</option>';
strHTML += '<option value="Other: JP Morgan Chase Building">Other: JP Morgan Chase Building</option>';
strHTML += '<option value="Other: Kid Junction">Other: Kid Junction</option>';
strHTML += '<option value="Other: Kings Dominion">Other: Kings Dominion</option>';
strHTML += '<option value="Other: Kinsley Commons Clcp">Other: Kinsley Commons Clcp</option>';
strHTML += '<option value="Other: Laser Quest">Other: Laser Quest</option>';
strHTML += '<option value="Other: Laurel Grove School">Other: Laurel Grove School</option>';
strHTML += '<option value="Other: Luray Caverns">Other: Luray Caverns</option>';
strHTML += '<option value="Other: Manassas Battlefield">Other: Manassas Battlefield</option>';
strHTML += '<option value="Other: Marriot">Other: Marriot</option>';
strHTML += '<option value="Other: Martha Washington Library">Other: Martha Washington Library</option>';
strHTML += '<option value="Other: Mary Washington College">Other: Mary Washington College</option>';
strHTML += '<option value="Other: Maryland Science Center">Other: Maryland Science Center</option>';
strHTML += '<option value="Other: Marymount University">Other: Marymount University</option>';
strHTML += '<option value="Other: Mclean Project For The Arts">Other: Mclean Project For The Arts</option>';
strHTML += '<option value="Other: Meadowlark Botanical Gardens">Other: Meadowlark Botanical Gardens</option>';
strHTML += '<option value="Other: Medieval Times">Other: Medieval Times</option>';
strHTML += '<option value="Other: Monster Mini Golf">Other: Monster Mini Golf</option>';
strHTML += '<option value="Other: Mount Saint Marys University">Other: Mount Saint Marys University</option>';
strHTML += '<option value="Other: Nancy F. Sprague Ctr">Other: Nancy F. Sprague Ctr</option>';
strHTML += '<option value="Other: Nasa Goddard">Other: Nasa Goddard</option>';
strHTML += '<option value="Other: National Aquarium">Other: National Aquarium</option>';
strHTML += '<option value="Other: National Geospatial Intelligence Agency">Other: National Geospatial Intelligence Agency</option>';
strHTML += '<option value="Other: National Harbor">Other: National Harbor</option>';
strHTML += '<option value="Other: National Inventors Hall Of Fame">Other: National Inventors Hall Of Fame</option>';
strHTML += '<option value="Other: National Reconnaissance Office">Other: National Reconnaissance Office</option>';
strHTML += '<option value="Other: Navy Federal Credit Union">Other: Navy Federal Credit Union</option>';
strHTML += '<option value="Other: Navy: Marcine Corps Memorial Stadium">Other: Navy: Marcine Corps Memorial Stadium</option>';
strHTML += '<option value="Other: New Market Battlefield">Other: New Market Battlefield</option>';
strHTML += '<option value="Other: Norman Cole Pollution Control Plant">Other: Norman Cole Pollution Control Plant</option>';
strHTML += '<option value="Other: Northrop Grumman :  Mclean, Va">Other: Northrop Grumman :  Mclean, Va</option>';
strHTML += '<option value="Other: Nysmith School For The Gifted">Other: Nysmith School For The Gifted</option>';
strHTML += '<option value="Other: Omni Shorham Hotel">Other: Omni Shorham Hotel</option>';
strHTML += '<option value="Other: Pennino Building">Other: Pennino Building</option>';
strHTML += '<option value="Other: Pfitzner Stadium">Other: Pfitzner Stadium</option>';
strHTML += '<option value="Other: Pirates Cove Waterpark">Other: Pirates Cove Waterpark</option>';
strHTML += '<option value="Other: Planetarium">Other: Planetarium</option>';
strHTML += '<option value="Other: Pohick Regional Library">Other: Pohick Regional Library</option>';
strHTML += '<option value="Other: Potomac School">Other: Potomac School</option>';
strHTML += '<option value="Other: President Lincolns Cottage">Other: President Lincolns Cottage</option>';
strHTML += '<option value="Other: Prince Georges Sports Complex & Learning Ctr">Other: Prince Georges Sports Complex & Learning Ctr</option>';
strHTML += '<option value="Other: Prince William Co Fairgrounds">Other: Prince William Co Fairgrounds</option>';
strHTML += '<option value="Other: Prince William Co Sports Complex">Other: Prince William Co Sports Complex</option>';
strHTML += '<option value="Other: Pump It Up">Other: Pump It Up</option>';
strHTML += '<option value="Other: Quest Diagnostic">Other: Quest Diagnostic</option>';
strHTML += '<option value="Other: Reagan National Airport">Other: Reagan National Airport</option>';
strHTML += '<option value="Other: Reston Farm Market">Other: Reston Farm Market</option>';
strHTML += '<option value="Other: Reston Sheraton Hotel">Other: Reston Sheraton Hotel</option>';
strHTML += '<option value="Other: Reston Wiehle Metro Station">Other: Reston Wiehle Metro Station</option>';
strHTML += '<option value="Other: Rock The Spectrum Gym">Other: Rock The Spectrum Gym</option>';
strHTML += '<option value="Other: Roer Zoofari">Other: Roer Zoofari</option>';
strHTML += '<option value="Other: Safeway">Other: Safeway</option>';
strHTML += '<option value="Other: Scotts Run Nature Preserve">Other: Scotts Run Nature Preserve</option>';
strHTML += '<option value="Other: Shady Grove University">Other: Shady Grove University</option>';
strHTML += '<option value="Other: Shenandoah University">Other: Shenandoah University</option>';
strHTML += '<option value="Other: Sideburn Center">Other: Sideburn Center</option>';
strHTML += '<option value="Other: Six Flags :  Maryland">Other: Six Flags :  Maryland</option>';
strHTML += '<option value="Other: Skate : N:  Fun Zone">Other: Skate : N:  Fun Zone</option>';
strHTML += '<option value="Other: Skyline Caverns">Other: Skyline Caverns</option>';
strHTML += '<option value="Other: Sportrock Climbing Center">Other: Sportrock Climbing Center</option>';
strHTML += '<option value="Other: Sports Bounce Of Loudoun">Other: Sports Bounce Of Loudoun</option>';
strHTML += '<option value="Other: Sprotrock Climbing Center">Other: Sprotrock Climbing Center</option>';
strHTML += '<option value="Other: Sprout Therapeutic Riding Center">Other: Sprout Therapeutic Riding Center</option>';
strHTML += '<option value="Other: St. James Sports And Wellness Center">Other: St. James Sports And Wellness Center</option>';
strHTML += '<option value="Other: St. Mary Church On Sideburn Road">Other: St. Mary Church On Sideburn Road</option>';
strHTML += '<option value="Other: St. Stephens & St. Agnes School">Other: St. Stephens & St. Agnes School</option>';
strHTML += '<option value="Other: Station 26 :  Edsall Road">Other: Station 26 :  Edsall Road</option>';
strHTML += '<option value="Other: Station 3 :  City Of Fairfax">Other: Station 3 :  City Of Fairfax</option>';
strHTML += '<option value="Other: Sully District Police Station">Other: Sully District Police Station</option>';
strHTML += '<option value="Other: Sully Plantation">Other: Sully Plantation</option>';
strHTML += '<option value="Other: Sunrise Assisted Living">Other: Sunrise Assisted Living</option>';
strHTML += '<option value="Other: Thomas Jefferson Library">Other: Thomas Jefferson Library</option>';
strHTML += '<option value="Other: Thompson Wildlife Management Area">Other: Thompson Wildlife Management Area</option>';
strHTML += '<option value="Other: Thrill Zone">Other: Thrill Zone</option>';
strHTML += '<option value="Other: Top Golf">Other: Top Golf</option>';
strHTML += '<option value="Other: Torpedo Factory Art Center">Other: Torpedo Factory Art Center</option>';
strHTML += '<option value="Other: Trinity Christian School">Other: Trinity Christian School</option>';
strHTML += '<option value="Other: Trinity United Methodist Church">Other: Trinity United Methodist Church</option>';
strHTML += '<option value="Other: United States Naval Academy">Other: United States Naval Academy</option>';
strHTML += '<option value="Other: University Of Mary Washington">Other: University Of Mary Washington</option>';
strHTML += '<option value="Other: Uptown Alley">Other: Uptown Alley</option>';
strHTML += '<option value="Other: Vienna Metro Station">Other: Vienna Metro Station</option>';
strHTML += '<option value="Other: Virginia Tech Thinkabit Lab">Other: Virginia Tech Thinkabit Lab</option>';
strHTML += '<option value="Other: Vulcan Quarry">Other: Vulcan Quarry</option>';
strHTML += '<option value="Other: Walker Nature Education Center">Other: Walker Nature Education Center</option>';
strHTML += '<option value="Other: Water Mine">Other: Water Mine</option>';
strHTML += '<option value="Other: Water Treatment Plant">Other: Water Treatment Plant</option>';
strHTML += '<option value="Other: Waterford">Other: Waterford</option>';
strHTML += '<option value="Other: West Springfield District Police Station">Other: West Springfield District Police Station</option>';
strHTML += '<option value="Other: Willow Oaks">Other: Willow Oaks</option>';
strHTML += '<option value="Other: Willston Multiculteral Center">Other: Willston Multiculteral Center</option>';
strHTML += '<option value="Other: Witter Athletic Fields">Other: Witter Athletic Fields</option>';
strHTML += '<option value="Other: Wolf Trap">Other: Wolf Trap</option>';
strHTML += '<option value="Other: Woodland Hill Retirement Home">Other: Woodland Hill Retirement Home</option>';
strHTML += '<option value="Other: Woodland Plantation">Other: Woodland Plantation</option>';
strHTML += '<option value="Other: Yorkville Clcp">Other: Yorkville Clcp</option>';
strHTML += '<option value="Park: Accotink Creek">Park: Accotink Creek</option>';
strHTML += '<option value="Park: Barcroft (Arlington)">Park: Barcroft (Arlington)</option>';
strHTML += '<option value="Park: Bluemont">Park: Bluemont</option>';
strHTML += '<option value="Park: Bull Run Regional">Park: Bull Run Regional</option>';
strHTML += '<option value="Park: Burke Lake">Park: Burke Lake</option>';
strHTML += '<option value="Park: Calvert Cliffs State">Park: Calvert Cliffs State</option>';
strHTML += '<option value="Park: Claude Moore">Park: Claude Moore</option>';
strHTML += '<option value="Park: Clemyjontri">Park: Clemyjontri</option>';
strHTML += '<option value="Park: Cub Run">Park: Cub Run</option>';
strHTML += '<option value="Park: Dulles Golf Center & Sports">Park: Dulles Golf Center & Sports</option>';
strHTML += '<option value="Park: Edsall Center">Park: Edsall Center</option>';
strHTML += '<option value="Park: Ellanor C. Lawrence">Park: Ellanor C. Lawrence</option>';
strHTML += '<option value="Park: Eugene Simpson">Park: Eugene Simpson</option>';
strHTML += '<option value="Park: Flight Trampoline">Park: Flight Trampoline</option>';
strHTML += '<option value="Park: Fort Hunt">Park: Fort Hunt</option>';
strHTML += '<option value="Park: Franconia">Park: Franconia</option>';
strHTML += '<option value="Park: Frying Pan">Park: Frying Pan</option>';
strHTML += '<option value="Park: Funland">Park: Funland</option>';
strHTML += '<option value="Park: Glen Echo :  Md">Park: Glen Echo :  Md</option>';
strHTML += '<option value="Park: Gravelly Point">Park: Gravelly Point</option>';
strHTML += '<option value="Park: Great Falls">Park: Great Falls</option>';
strHTML += '<option value="Park: Great Meadows (The Plains)">Park: Great Meadows (The Plains)</option>';
strHTML += '<option value="Park: Green Spring Garden">Park: Green Spring Garden</option>';
strHTML += '<option value="Park: Gunpowder Falls State">Park: Gunpowder Falls State</option>';
strHTML += '<option value="Park: Hemlock Overlook">Park: Hemlock Overlook</option>';
strHTML += '<option value="Park: Huntley Meadows">Park: Huntley Meadows</option>';
strHTML += '<option value="Park: Jefferson District Golf Course">Park: Jefferson District Golf Course</option>';
strHTML += '<option value="Park: Jefferson Mini Golf">Park: Jefferson Mini Golf</option>';
strHTML += '<option value="Park: Kenilworth">Park: Kenilworth</option>';
strHTML += '<option value="Park: Lake Accotink">Park: Lake Accotink</option>';
strHTML += '<option value="Park: Lake Fairfax">Park: Lake Fairfax</option>';
strHTML += '<option value="Park: Leesburg Animal">Park: Leesburg Animal</option>';
strHTML += '<option value="Park: Leesylvania State">Park: Leesylvania State</option>';
strHTML += '<option value="Park: Lewinsville">Park: Lewinsville</option>';
strHTML += '<option value="Park: Loriella State">Park: Loriella State</option>';
strHTML += '<option value="Park: Mason District">Park: Mason District</option>';
strHTML += '<option value="Park: Mason Neck">Park: Mason Neck</option>';
strHTML += '<option value="Park: Nationals">Park: Nationals</option>';
strHTML += '<option value="Park: Nottoway">Park: Nottoway</option>';
strHTML += '<option value="Park: Ossian Hall">Park: Ossian Hall</option>';
strHTML += '<option value="Park: Pohick Bay">Park: Pohick Bay</option>';
strHTML += '<option value="Park: Pohick Bay Regional & Golf Course">Park: Pohick Bay Regional & Golf Course</option>';
strHTML += '<option value="Park: Pole Green">Park: Pole Green</option>';
strHTML += '<option value="Park: Potomac Crossing">Park: Potomac Crossing</option>';
strHTML += '<option value="Park: Potomac Overlook Regional">Park: Potomac Overlook Regional</option>';
strHTML += '<option value="Park: Prince William Forest">Park: Prince William Forest</option>';
strHTML += '<option value="Park: Quincy">Park: Quincy</option>';
strHTML += '<option value="Park: Redskin">Park: Redskin</option>';
strHTML += '<option value="Park: Riverbend">Park: Riverbend</option>';
strHTML += '<option value="Park: Rocky Run">Park: Rocky Run</option>';
strHTML += '<option value="Park: Rope Adventure">Park: Rope Adventure</option>';
strHTML += '<option value="Park: Sandy Run Regional">Park: Sandy Run Regional</option>';
strHTML += '<option value="Park: Simpson">Park: Simpson</option>';
strHTML += '<option value="Park: Splash Down Water">Park: Splash Down Water</option>';
strHTML += '<option value="Park: Temple Hall Farm Regional">Park: Temple Hall Farm Regional</option>';
strHTML += '<option value="Park: University Of Maryland, College">Park: University Of Maryland, College</option>';
strHTML += '<option value="Park: Upton Hill Regional">Park: Upton Hill Regional</option>';
strHTML += '<option value="Park: Wakefield Skate">Park: Wakefield Skate</option>';
strHTML += '<option value="Park: Watkins Regional">Park: Watkins Regional</option>';
strHTML += '<option value="Park: Word Of Grace / Old Redskin">Park: Word Of Grace / Old Redskin</option>';
strHTML += '<option value="Park: Zoofari Animal">Park: Zoofari Animal</option>';
strHTML += '<option value="Reccenter: Claude Moore">Reccenter: Claude Moore</option>';
strHTML += '<option value="Reccenter: Lee District">Reccenter: Lee District</option>';
strHTML += '<option value="Recenter: Audrey Moore">Recenter: Audrey Moore</option>';
strHTML += '<option value="Recenter: Cub Run">Recenter: Cub Run</option>';
strHTML += '<option value="Recenter: George Washington">Recenter: George Washington</option>';
strHTML += '<option value="Recenter: Lee">Recenter: Lee</option>';
strHTML += '<option value="Recenter: Lee District">Recenter: Lee District</option>';
strHTML += '<option value="Recenter: Mount Vernon">Recenter: Mount Vernon</option>';
strHTML += '<option value="Recenter: Mt Vernon">Recenter: Mt Vernon</option>';
strHTML += '<option value="Recenter: Oak Marr">Recenter: Oak Marr</option>';
strHTML += '<option value="Recenter: Providence">Recenter: Providence</option>';
strHTML += '<option value="Recenter: South Run">Recenter: South Run</option>';
strHTML += '<option value="Recenter: Spring Hill">Recenter: Spring Hill</option>';
strHTML += '<option value="Recenter: Wakefield">Recenter: Wakefield</option>';
strHTML += '<option value="Theater: Adventure Theatre">Theater: Adventure Theatre</option>';
strHTML += '<option value="Theater: Amc">Theater: Amc</option>';
strHTML += '<option value="Theater: Arena Stage">Theater: Arena Stage</option>';
strHTML += '<option value="Theater: Bow Tie Cinema">Theater: Bow Tie Cinema</option>';
strHTML += '<option value="Theater: Cinemark">Theater: Cinemark</option>';
strHTML += '<option value="Theater: Cobb Village 12">Theater: Cobb Village 12</option>';
strHTML += '<option value="Theater: Constellation Theatre">Theater: Constellation Theatre</option>';
strHTML += '<option value="Theater: Hylton Performing Arts Center">Theater: Hylton Performing Arts Center</option>';
strHTML += '<option value="Theater: Imagination Stage">Theater: Imagination Stage</option>';
strHTML += '<option value="Theater: Regal">Theater: Regal</option>';
strHTML += '<option value="Theater: Synetic Theatre">Theater: Synetic Theatre</option>';
strHTML += '<option value="Theater: University Mall Theater">Theater: University Mall Theater</option>';
document.getElementById(`ftselector${optVal}`).innerHTML = strHTML;
